### ISSUE TITLE
Feedback on "Building Docker Images for .NET Core Applications"

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/core-docs#1013]
The following are some review comments I have on the [Building Docker Images for .NET Core Applications](https://docs.microsoft.com/en-us/dotnet/articles/core/docker/building-net-docker-images) documentation.

1. _Docker Image Optimizations - Production_ This section references fast deploy and start time.  Another important aspect of production images that isn't mentioned is around the required space to run a container and achieving high disk density across the running containers.  In the case of .NET, by having the shared framework in the base image, you amortize its size across the number of containers running on the same host because you are able to share the layer.
2. _Docker image variations-sdk_ This section references has the wrong tag for the sdk image - microsoft/dotnet-preview2-sdk.  It should be microsoft/dotnet:1.0.0-preview2-sdk note the version and the tag separator.
3. _Alternative images - onbuild_ This section should reference the versions onbuild tag to be consistent with the other image descriptions - e.g. microsoft/dotnet:1.0.0-preview2-onbuild vs microsoft/dotnet:onbuild.  The versioned onbuild images should also appear in the block that lists the various images and their sizes.
4. _Prerequisites_ I see Docker for Windows or Docker for Mac is required.  What is the limitation on using Linux?
5. _Creating the Web API application_ I was a little surprised to see "before we containerize the application, first run the application locally".  I was expecting that the development image would be used.  The whole purpose of having a development image is so that you do not have configure a machine.  You should be able to use a predefined image (with maybe some additions to add some preferred or optional tools).

@spboyer, @dleeapho

**Comment by spboyer** [comment]
@MichaelSimons 

1. Added
1. edit made
1. edit made
1. There is no limitation on Linux, the assumption is being made that OSX and Windows is the primary dev platform
1. It is noted that this is a reference point, are we to assume that the dev has not setup their machine for any .NET development locally? Would the same be true for another platform (node, Java, php)

@stevelasker
