### ISSUE TITLE
Update docs to .NET Core 1.0.1?

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#1020]
We're shipping a patch version today. Do we need to review our content to make sure is up-to-date? Do we need to add content about how versioning works?

What are the things we need to be concerned about? sdk version, TFM name, specific mentions of .NET Core 1.0, samples?
At least [this topic](https://docs.microsoft.com/en-us/dotnet/articles/standard/frameworks) needs to be updated to say the latest is 1.0.1. But what else, since we're recommending customers to move to the latest in order to get support.

Also, should we create a branch with the name 1.0.0 before start making these changes?

@richlander, can you shed some light into this?

**Comment by cartermp** [comment]
The F# doc that covers using the .NET SDK tools will have to be updated to be _much_ shorter.

**Comment by mairaw** [comment]
Other topics that we probably need to be updated too since we have F# support now:
https://github.com/dotnet/core-docs/blob/master/docs/core/index.md
https://github.com/dotnet/core-docs/blob/master/docs/standard/index.md

They both say only C# is supported.

**Comment by mairaw** [comment]
Windows prerequisites topic should also be updated to point to 1.0.1 new tooling link:
https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites

**Comment by mairaw** [comment]
I've created the branch since we were going start merging PRs for 1.0.1 release. It's here: https://github.com/dotnet/core-docs/tree/1.0.0

**Comment by mairaw** [comment]
I'm not aware of any additional changes that need to be done due to 1.0.1 release. So closing this issue.
