### ISSUE TITLE
Invalid links in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#1044]
I have found few links in API reference that are not valid:

* [`ResourceManager`](https://docs.microsoft.com/en-us/dotnet/core/api/system.resources.resourcemanager) and some other types contain the following note:

 > **Security Note**: Calling methods in this class with untrusted data is a security risk. Call the methods in the class only with trusted data. For more information, see [Untrusted Data Security Risks](http://curah.microsoft.com/57301/security-some-apis-are-not-necessarily-appropriate-for-untrusted-input).

 The link leads to http://curah.microsoft.com, which does not seem to be a valid domain name. A quick search lead me to https://docs.com/rick-anderson-1/8710/untrusted-data-security-risks by @Rick-Anderson, is that the correct URL?

* The description for the `activationAttributes` parameter of [`_Assembly.CreateInstance`](https://docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices._assembly#System_Runtime_InteropServices__Assembly_CreateInstance_System_String_System_Boolean_System_Reflection_BindingFlags_System_Reflection_Binder_System_Object___System_Globalization_CultureInfo_System_Object___) is:

 > An array of type Object containing one or more activation attributes that can participate in the activation. An example of an activation attribute is:

 > URLAttribute([http://hostname/appname/objectURI](http://hostname/appname/objectURI))

 Since the URL is not meant to be a valid URL, it should not be a link.

**Comment by mairaw** [comment]
Thanks @svick!
 
I can fix the first link as soon as we can confirm with @Rick-Anderson the right target. This has to be fixed on MSDN too.

I have a fix in place for the second issue you pointed out. I just need to wait for the publishing system to pick up that change so I can validate and push it live.

**Comment by Rick-Anderson** [comment]
Yes, that's where Curah was moved to.

**Comment by mairaw** [comment]
Thanks for confirming @Rick-Anderson. I'll make the fixes!

**Comment by mairaw** [comment]
The MSDN topics that had that Curah link are fixed:
https://msdn.microsoft.com/en-us/library/system.resources.resourcemanager(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.resources.resourcereader(v=vs.110).aspx
https://msdn.microsoft.com/en-us/library/system.resources.resourceset(v=vs.110).aspx

**Comment by mairaw** [comment]
This is fixed on docs now. Thanks @svick!
