### ISSUE TITLE
Suggestions for Overview of .NET Implementations topic

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#105]
* The opening paragraph seems very vague. If I'm a newbie or non-developer and somehow land on this topic, what do I use the .NET platform and these standards for?

.NET Core section
* You introduce the list of characteristics like this "There are several characteristics of .NET Core:", but you're actually listing the main ones. Maybe it'd be good to be more specific.
* I'd use a more common word than boon. Maybe advantage or gain?
* The list of characteristics doesn't look uniform. Some are written as paragraphs, some as list items. It'd be good to have a consistent behavior.
* For cross-platform support, is it really about running on the best environment? Or is it about the different environment offerings we have out there?
* For open source: Should we also mention the transparency aspect of open source? Or having the community helping shape the future of .NET Core? The description seems really minimal.
* For application isolation, instead of "take" wouldn't be better to say embed?

.NET Framework
* It should be .NET Framework Class Library not Framework Class Libraries. Also, should it link to the library on MSDN?
* I would avoid using the apostrophe (') there to show possession. So instead of "Windows Forms' strength" I'd say "The strength of Windows Forms" and for the second one, I'd just remove the apostrophe.
* "that is suited for your use case" or "that is best suited for your use case"?
* I don't get what MVC does based on the description. Should we talk about patterns or separation of concerns here? The link you point to has a good brief description

.NET native
* fix punctuation here: (such as C#, Visual Basic, F# etc.)
* put (IL) after "Intermediate Language"
* Maybe this sentence: "IL is then picked up by the runtime, and Just-In-Time compiled at run-time to machine code." could be better explained as "At run-time, a just-in-time (JIT) compiler translates the IL into native code" (or machine code)
* .NET Native NET Native - remove duplication
* Should we link to https://msdn.microsoft.com/en-us/library/windows/apps/dn726767.aspx, where you mention UWP apps?

**Comment by blackdwarf** [comment]
Good one, let me make a PR for fixing these.

**Comment by blackdwarf** [comment]
Some comments on this @mairaw:

.NET Core:

* "Take" is better because "embed" has different semantics. I will change the word to be slightly nicer. 
* Well, I didn't want to have any specific MVC things in there since I already have the link in there, so...

That's it for me, will be making a PR with these. Though, I suspect most of this document needs to change but this are bigger changes.

**Comment by mairaw** [comment]
@blackdwarf 
1 - Sounds good regarding "take"
2- I don't think you have to drill down on the concepts either. But MVC has a couple of keywords that I personally think would be interesting to throw in there.

Also found a typo: loging should be logging.

Thanks!
