### ISSUE TITLE
[docs/core/tools/dotnet-pack.md] Clarify how dependency works for dotnet-pack command

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#1070]
There are some LiveFyre comments about the documentation being inaccurate when describing how to package project-to-project references. We need to address those comments and make sure the topic is correct.

https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-pack

@blackdwarf, let me know how you'd like to proceed on this one.

**Comment by blackdwarf** [comment]
@mairaw I suggest you change the docs to reflect the behavior that the `type: build` will also not get packaged. However, there will be a new implementation of `dotnet pack` coming as part of the overall work of moving off of project.json and onto csproj, so things are going to be changing as well.

Overall, I have made an issue here that we need a doc that explains how dependencies are done for .NET Core and I still believe a higher-level overview would be better. I'm not sure that command reference is a good place to go in depth on how NuGet packages are created and what is the philosophy around dependency management in .NET Core overall, though I could be wrong.

**Comment by mairaw** [comment]
I agree with you @blackdwarf. There's another issue that I've tagged you this morning asking us to create a topic on package resolution. Is that what you had in mind or do you have another issue tracking that?
But I still think we should make sure the information on dotnet-pack is accurate and then having a separate high-level overview to link to for more info when that's ready.
