### ISSUE TITLE
TOC isn't expanded for the topic: A Tour of the C# Language

### ISSUE THREAD

**Issue by badersur** [dotnet/core-docs#1074]
Table of contents is not expanded for the topic: [A Tour of the C# Language](https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/index) in the left sidebar.

**Comment by svick** [comment]
It is, if you use the URL https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/, instead of https://docs.microsoft.com/en-us/dotnet/articles/csharp/tour-of-csharp/index.

In the long term, I think both URLs should either behave the same or one of them should be a redirect.

In the short term, how did you get to the /index URL? Is there a link to it somewhere?

**Comment by badersur** [comment]
It seems like **all** URLs that have `/index` don't show the TOC!

I got to it from the links in [C# Guide](https://docs.microsoft.com/en-us/dotnet/articles/csharp/). Most of them have `/index`.

**Comment by mairaw** [comment]
Yeah, a recent change to the site caused this issue. We'll have a fix for this but I don't know when. I'll try to find where we have links with `/ index` on them. We fixed the one we had one the homepage that I've noticed before.

**Comment by mairaw** [comment]
Actually, it doesn't make much sense to change the links. But I'll make sure I call out this scenario in the tracking bug we have for this.

**Comment by mairaw** [comment]
This is now fixed!

**Comment by badersur** [comment]
Thanks for the fix and the new blue marker :)

**Comment by mairaw** [comment]
Thank @DuncanmaMSFT's team 😄

**Comment by badersur** [comment]
Thanks to you Mr. @DuncanmaMSFT and your team :)

There is an issue with the [SDK page](https://docs.microsoft.com/en-us/dotnet/articles/core/sdk); it doesn't show the marker! Maybe because it is not in the [toc.md](https://github.com/dotnet/core-docs/blob/master/docs/toc.md)?!

**Comment by mairaw** [comment]
Yes, it's not there. I have an issue tracking this topic: #781
