### ISSUE TITLE
API reference?

### ISSUE THREAD

**Issue by xen2** [dotnet/core-docs#109]
Just wondering, what are the plans for BCL API reference? (available at http://dotnet.readthedocs.org/en/latest/bcl/api-ref.html )

Generated by an external tool?
How does it integrate in Sphinx workflow?
What tool/work would be necessary?

**Comment by BethMassi** [comment]
Hi @xen2 - thanks for the interest! @blackdwarf can elaborate but basically we're looking at generating the reference docs and putting them here soon.

**Comment by xen2** [comment]
Ok thanks, interested to know what you did there, and see if we can also use it later instead of rolling our own.

So far what I did is I made https://github.com/SiliconStudio/SharpDoc (made by coworker @xoofx) outputs .rst with raw html (by changing templates), and it resulted in quite nicely integrated doc with ReadTheDoc theme. If you are interested, I can update this thread with live demo when it will be online!

**Comment by mairaw** [comment]
Just saw this issue. The API docs now live in this site: https://dotnet.github.io/api/index.html

It was generated using a tool called docfx. The documentation was supposed to be here (dotnet.github.io/docfx) but the site seems down at the moment. @blackdwarf, do you know anything about it?

@chenkennt I also see on the nuget page (https://www.nuget.org/packages/docfx/), that we had a release this week. Does that mean the release is now public and available for customers to use it too?

**Comment by xen2** [comment]
@mairaw We already switched to docfx 10 days ago (2 days after http://qinezh.github.io/docfx/ went public, we were lucky to find it right after it went covertly live)

We use it for Xenko Game Engine:
- api: http://doc.xenko.com/1.4/api/SiliconStudio.Xenko.Engine.html
- manual: http://doc.xenko.com/1.4/manual/index.html
- github: https://github.com/SiliconStudio/xenko-docs

Works well and quite fast to generate doc!

Thanks @blackdwarf and @BethMassi

**Comment by mairaw** [comment]
Awesome @xen2!
