### ISSUE TITLE
Document Offline Install for .NET Core VS SDK

### ISSUE THREAD

**Issue by terrajobst** [dotnet/core-docs#1094]
You can currently not download an offline installer for the .NET Core VS SDK. Instead, you have to download the regular boostrapper and run it with a command line option (such as `/layout c:\Foo`) to get an offline layout.

TOC wise, I'm not entirely sure where the best place it, but it should probably be linked from there:

https://docs.microsoft.com/en-us/dotnet/articles/core/getting-started

**Comment by joeloff** [comment]
We should probably also mention that because it's a full layout, it will download all the packages for all supported languages, ~1GB.
