### ISSUE TITLE
Looping in list documentation is redundant and incomplete

### ISSUE THREAD

**Issue by breyed** [dotnet/core-docs#1101]
The [Lists](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/lists) docs has redundant examples for `listOfSquares` and `squaresList`. Neither specifies the rules for `for` in a list. There is a reference to Sequence Expressions, but no description of how `for` differs in its usage in list versus a sequence.

**Comment by cartermp** [comment]
Good catch, @breyed.  In this case, because each code sample has exactly the same semantics, the best way to address this would probably be to delete the first example.
