### ISSUE TITLE
Looking for writing guidelines

### ISSUE THREAD

**Issue by BillWagner** [dotnet/core-docs#116]
I read the contributing.md and the process for contributing is clear. 

However, it needs to have some guidance on the writing style. For example:
Should tutorials be in 1st, 2nd or 3rd person?
Should they be more conversational, or more academic?
Active voice, or passive voice?

I looked at a few articles, and I can see a mix. 
I'd recommend 2nd person, conversational, and active voice, based on the target audience you've defined.

What do others think? esp. @BethMassi @richlander

**Comment by cartermp** [comment]
+1.  This is how I've been writing things right now, and think they should be written.

**Comment by mairaw** [comment]
I agree.

**Comment by BethMassi** [comment]
+1 for active voice. Here's some guidance for "hero" content (Getting started, conceptual / beginner): 

1) Keep it simple – hero tutorials are concise and short.  Within the first 5 minutes the user should have something running / built / accomplished. 

2) Use smaller words – We have an international audience reading English. if you write the tutorial assuming a 5th grade reading level people understand it better.

3) Show the scenario you are covering for multiple backgrounds. i.e. Users coming from a Linux background vs. a Windows vs. Mac. 

4) While the goal is to keep the articles as concise as possible, also make sure you leave the users in a good, accomplished state.  If you're asking yourself "where am I now?" at the end of the article, you're not finished.
