### ISSUE TITLE
MSDN links should be language neutral

### ISSUE THREAD

**Issue by ghogen** [dotnet/core-docs#121]
Existing links to MSDN have en-us in the path.  To make them more useful globally, the en-us should be stripped out of the path.

for example in docs/concepts/common_type_system.md
we have

*   [Common Type System](https://msdn.microsoft.com/en-us/library/vstudio/zcx1eb1e%28v=vs.100%29.aspx)
*   [Common Language Specification](https://msdn.microsoft.com/en-us/library/vstudio/12a7a7h3%28v=vs.100%29.aspx)

**Comment by ghogen** [comment]
Ideally we would also have something in the guidelines for contributors about how to input these links.

**Comment by mairaw** [comment]
I agree with @ghogen that we should omit the version number on those links.

**Comment by blackdwarf** [comment]
@mairaw will assign to you. :)

**Comment by mairaw** [comment]
Sounds good

**Comment by seandebutts** [comment]
@mairaw, I simplified the MSDN URLs per our conversation: https://github.com/dotnet/core-docs/pull/279/files

I removed "/en-us", the version number, and "/vstudio/". Look good?

cc: @blackdwarf @ghogen

**Comment by mairaw** [comment]
Need to add this info to the contributing guide but existing links were fixed
