### ISSUE TITLE
Topics not in the TOC and blockquote

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#123]
As I'm starting to validate the files I have in my cloned core-docs folder, I'm finding topics that are there but not in the TOC. Is that by design? Should I even be looking at those?
For example:
https://github.com/dotnet/core-docs/blob/master/docs/concepts/assembly-format.rst
https://github.com/dotnet/core-docs/blob/master/docs/concepts/class-libraries.rst

Also, for the first topic above, when converted to MD, the second paragraph is using a blockquote (">"). Is that the intended result? Or do we want to just indent the paragraph?

**Comment by blackdwarf** [comment]
Yes, because these are pointed to by some other documents. Not everything is accessible directly from  the TOC.

**Comment by mairaw** [comment]
Ok, this is somewhat different than what we do for the framework docs.

And what about the blockquote? By design too? Or should we just indent the paragraph.

**Comment by mairaw** [comment]
I also noticed that you lose all menus if you navigate to a topic not in TOC. By design?
See http://dotnet.github.io/docs/concepts/native-interop.html for an example.

/cc @blackdwarf @chenkennt

**Comment by chenkennt** [comment]
Currently if the topic is not in TOC, there will be no TOC shown in this topic, as we cannot figure out which TOC the topic belongs to. But I agree this is not a good user experience, as user cannot navigate to other places from this page. Which behavior do you expect? Just show a navbar, or you want to show some TOC even the topic is not in any TOC? @mairaw

**Comment by mairaw** [comment]
If possible, I think the best would be to show the navbar and the TOC with no selection, similar to how it was done in RTD: http://dotnet.readthedocs.org/en/latest/concepts/native-interop.html

Do you guys agree @richlander and @blackdwarf?

**Comment by blackdwarf** [comment]
Yes, that would be best. Like this, there is no way for people to go back. Either TOC or breadcrumbs, but TOC would be best.

**Comment by blackdwarf** [comment]
@chenkennt assigning this to you for now.

**Comment by vicancy** [comment]
Topics not in TOC is now showing its nearest TOC, for example, http://dotnet.github.io/docs/tutorials/getting-started-with-csharp/console-teleprompter.html
