### ISSUE TITLE
Conversion issues found for topic "Async Programming in C#/VB"

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#125]
Ref: http://dotnet.readthedocs.org/en/latest/async/async-csharp-vb.html

- Code blocks are not rendering properly: some are not rendering as code and some are inside a block but not the entire sample, just parts of it
- Use of blockquote for two of the bulleted lists seems wrong
- The table Use this / Instead of this / When wishing to do this is unreadable in MD

**Comment by cartermp** [comment]
Putting some issues here:

- [Title falls off the edge of the margin on index](http://dotnet.github.io/docs/async/async-index.html)
- [Table at the bottom is missing](http://dotnet.github.io/docs/async/async-csharp-vb.html)
- [The "#" in "F#" is missing in all headers](http://dotnet.github.io/docs/async/async-fsharp.html)

**Comment by BethMassi** [comment]
Also found conversion issue on this one http://dotnet.github.io/docs/porting/supporting-core.html 
The images aren't displaying.

**Comment by cartermp** [comment]
Yup, looks like images are broken for all articles.

**Comment by blackdwarf** [comment]
Feel free to make a PR fixing it. :)

**Comment by cartermp** [comment]
I can get the first and last (rename title to be shorter and re-add the "#" that went missing in the conversion), but the table might be a bigger issue.  It renders as a valid markup table on Github and vscode, but doesn't show any borders on the site (thus making it hard to tell that it's a table).  I'm not familiar enough with the doc system to make a change to how tables are rendered.

**Comment by blackdwarf** [comment]
Ah, young padawan. :) I jest. I will take that. Please file issues for each of them so we can refer the properly. I will be fixing the CSS overall anyway.

**Comment by mairaw** [comment]
@blackdwarf and I are following up with Ken on the images issues. I don't know if they were ported to the new site.

For the table, it does look better on the site than it looked on my machine, which was all garbled. And the code samples also look ok here. Not sure why it was displaying differently on my machine when I was validating it locally.

**Comment by mairaw** [comment]
I think this one can also be closed. I think it refers to this topic https://docs.microsoft.com/en-us/dotnet/articles/csharp/async but the issues I've listed don't repro anymore
