### ISSUE TITLE
Remove unnecessary namespace qualifiers in C# LINQ Samples program.cs files

### ISSUE THREAD

**Issue by matthewreily** [dotnet/core-docs#142]
Program.cs files should all be contained within a namespace and we should remove any unnecessary namespace qualifiers.

**Comment by BethMassi** [comment]
@matthewreily just a tip, if you reference an issue in the PR then it will close automatically when we merge. Put "Fix #nnn" in the description of your PR

**Comment by matthewreily** [comment]
Thanks for the tip!
