### ISSUE TITLE
Contributing guidelines suggestions

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#148]
Re: https://github.com/dotnet/core-docs/blob/master/CONTRIBUTING.md

I think there are a couple of things that could be improved for the contributing guidelines:
1- We start the topic with the build process. This can be scary as the first thing you see to contribute. I imagine that not everybody contributing will need to build the docs. Am I wrong? Maybe we should explain when and who needs to do that.
2- The guidelines are written from the standpoint of building new articles. What if I just want to edit a topic that I found an issue with? Do I also need to file an issue and get approval?

/cc @BethMassi @blackdwarf

**Comment by blackdwarf** [comment]
@mairaw I didn't even see this issue. :) Some answers:

1. I think everyone would want to see if their changes work right? Consider in hte future when we have documents pulling in samples. You need to see if this works. 
2. Yes, of course. We need to make this explicit however, so good catch.

**Comment by cartermp** [comment]
Agreed with @blackdwarf.  Something like this?

"Before adding or editing content, submit an issue with a suggestion for your proposed additions and/or changes. If you are adding a new article, provide detail on what the it would discuss, and how it would relate to existing documentation."

**Comment by stevehoag** [comment]
LGTM


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by mairaw** [comment]
I can see a scenario where I just want to make simple fixes and would just make the changes and submit a PR. In this case, I don't need to build the docs and don't think people would need approval for that.
Maybe just start with the guidelines first and then explain how to build the docs later and why you need to build the docs. It might not be totally obvious the reason you wouldn't simply edit the md files and be done for a newbie.

Thoughts?

**Comment by blackdwarf** [comment]
@mairaw OK, for very simple changes this is ok. But, for instance, what happens if you decide to add a new file or you accidentaly change the title of a given MD file. Building actually warns you about this, because TOC will point to a file that doesn't exist (docfx fails the build with an error). 

if you are really, **really** only changing 1-2 lines, you can actually do that in the GH directly and make a PR from there, you don't really need to clone the entire repo. Maybe we can put that in the instructions. But I would want to have a clean PR for everything, really.

**Comment by mairaw** [comment]
Agree, that's what I've been doing because my contributions so far were only simple fixes. What do you mean with a clean PR @blackdwarf? 
You could also argue that the contributing guidelines are not for the simple fixes and not cover that scenario here. But my suggestions would still apply.

**Comment by blackdwarf** [comment]
@mairaw I mean that each contribution is backed by a PR.

**Comment by mairaw** [comment]
Makes sense @blackdwarf.

**Comment by blackdwarf** [comment]
Closed with #188
