### ISSUE TITLE
The "#" in headers for the F# async doc is missing

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#157]
The headers are missing "#".  Strangely, [the raw markdown](https://raw.githubusercontent.com/dotnet/core-docs/master/docs/async/async-fsharp.md) contains the character.

Unassigned myself because it's unfortunately not just a matter of adding it back in.

**Comment by mairaw** [comment]
Have you tried this @cartermp?
http://stackoverflow.com/questions/13537826/how-do-i-add-a-trailing-hash-to-a-header-in-github-flavored-markdown

**Comment by cartermp** [comment]
Tried adding the space and escaping with `\`.  Unfortunately neither worked.  I'd like to avoid adding the `♯` character if at all possible.  If there isn't a quick way to fix this I'll just rename the title and headers.

**Comment by mairaw** [comment]
I tried just adding the space and it seemed to work. Can you check?

**Comment by cartermp** [comment]
Just tried again, still doesn't work on my machine.  I'll pull down your PR and test it out.  Could be something funky with my editor.

**Comment by cartermp** [comment]
Was able to repro (with your fix) on two Windows machines.  I'm thinking it's an issue with the docfx parser.  The Github markdown parser seems to recognize the space and render the "#", but when build with the docfx tool it still won't show.

@chenkennt is there something being done on headers like a call to `.Trim()` that gets rid of whitespace at the end?

**Comment by chenkennt** [comment]
This is actually a by design behavior according to markdown spec. Adding a whitespace doesn't work for all markdown parsers (for example, VS Code). I'd recommend the following workaround:
1. Add another #, like this:
    # Async Programming in F# #
2. Use HTML encode, use &#35; to replace #

**Comment by cartermp** [comment]
Thanks for the info, @chenkennt!
