### ISSUE TITLE
TOC proposal

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/core-docs#173]
Just realized that making a PR would require actually moving all of the files around, creating new ones, deleting old ones and what not. Not a problem, but since no no. 1 attempt is good, better to first shake out the TOC proposal in an issue and then just do the work once we are settled.

Several notes:
* This covers only the .NET Core and Getting started content not the scenarios, as agreed in #152 
* The C# tutorials have been condensed from @stevehoag's issues since some things come naturally together (for instance, delegates and events)
* The "packaging" part has been merged with deployment, since after some thought I've come to realize it is pretty much the same (i.e. you have to package your application *somehow* to be able to deploy it)
* The absence of web apps is intentional, since no scenarios are in this proposal
* I keep thinking that the "installing" bit should just point to http://dotnet.github.io/getting-started and not replicate content that we will have to change in numerous places

With that, I give you the new proposal:

* Getting started
    * What is the .NET Platform?
    * Installing .NET Core 
        * Installing .NET Core on Linux
        * Installing .NET Core on OS X
        * Installing .NET Core on Windows
    * Setting up your development environment 
        * Developlment using VS Code
        * Developlment using Visual Studio
        * Developlment using vim
        * Developlment using Sumblime Text
    * Writing your first console application on .NET Core
* Learn C#
    * Syntax
    * Features at a glance
    * C# Type system
    * Iterators
    * Delegates & events
    * Generics
    * Language Integrated Query (LINQ)
    * Asynchronous programming
    * Paralell programming
    * Native interoperability
    * Reflection & code generation
    * Documenting your code   
* Understanding the .NET Core Platform 
    * What is .NET Core? Overview of the platform   
    * .NET Primer
    * Programming languages on .NET Platfrom
        * .NET - a multilanguage platform
        * The main trio: C#, F# and VB.NET
    * Writing console applications
        * Overview and moving pieces
        * Console applications paradigm 
        * Creating single binaries with native compilation
    * Writing libraries on .NET Core
        * Overview
        * Creating a class library
    * Understanding package management on .NET
        * Introducing NuGet
        * Working with Nuget Packages
        * Creating NuGet Packages
        * Publishing NuGet Packages
    * Packaging & Deploying applications
        * Deploying applications overview
        * Deploying to a shared runtime
        * Deploying self-contained applications
        * Deploying single binaries
        * Deploying NuGet packages
        * Deploying ASP.NET web applications
    * Porting applications between editions of .NET Platform
        * Overview
        * Tooling for helping the porting 
        * Porting your applications
        * Porting your libraries
        * Porting NuGet packages 
    * .NET Command Line Interface reference
        * Overview of the .NET Core Command Line Interface (dotnet CLI)
        * dotnet
        * dotnet-compile
        * dotnet-publish
        * dotnet-run
        * ... 
* API reference
    * Link to the ref docs

/cc @BethMassi @mairaw @stevehoag @cartermp @ghogen

**Comment by BethMassi** [comment]
LGTM

**Comment by cartermp** [comment]
LGTM :shipit:

**Comment by mairaw** [comment]
Overall, LGTM. A couple of points (some are picky I know):
- I think we should have the installing docs here too, since I'd imagine that would be a more comprehensive article showing the different ways you can install, etc.
- I understand that we don't want to cover the web scenarios in detail here but maybe we should have a topic (or a section in an existing topic) that explains the different scenarios you'll use .NET Core (console, libraries, web, etc.) and link to the ASP.NET site docs and the other sections on this TOC.
- The .NET Primer seems a bit lost there and I still don't like that title (I can't imagine anyone searching for that term for example)
- I also think that some of the titles should be more descriptive. For example, instead of just "overview" under each section, I'd say "Porting applications overview". We want to think of SEO as well when we design this TOC, right?
- How are we capitalizing the titles? Do we have a pattern? I see "Working with Nu**g**et **P**ackages" and "Deploying Nu**G**et **p**ackages"

**Comment by blackdwarf** [comment]
@mairaw some replies, in the order of questions asked:

1. I don't follow?
2. We will have that, and those will be in its own separate scenario heading. I just want to get this off the ground since we didn't finish the scenario dicussion in the other issue.
3. :)
4. Well, an overview usually has a different title. You can see the actual PR on #175 
5. Fixed this in #175 to be consistent.

Thanks!

**Comment by mairaw** [comment]
@blackdwarf:

1 - maybe I misunderstood what you meant by "I keep thinking that the "installing" bit should just point to http://dotnet.github.io/getting-started and not replicate content that we will have to change in numerous places". I thought you were saying you didn't want the installing topics.
2 - sounds great!
3 - sorry, I still don't have suggestions for a better name :-)
4,5 - ok, thanks!

It will be easier to discuss this further once we merge the new TOC. Thanks!

**Comment by blackdwarf** [comment]
@mairaw:

1. Nope, meant that the docs just point to the URL. :) I loathe having to edit content in 3 different places.
2. Good.
3. Then we are stuck with "Primer" until we do have a better name.

Do comment on #175 as well before I merge today.

**Comment by mairaw** [comment]
1. If it makes sense, I'm fine with that. But for example, the steps for Windows on the getting-started page is completely different from the topic.
3. I prefer something like "Lap around .NET" or "Key .NET Concepts". My 2 cents, of course!

I'll take a more closer look again at #175 right now.

**Comment by blackdwarf** [comment]
Let's try the mail thing see if it works.

The docs need to change to reflect the new reality that is on the Core site. What is on the site is the new true way to install bits. I was meaning to change these as soon as the TOC is merged. :))

Thanks,
Z

Sent from my tricorder




On Tue, Dec 1, 2015 at 10:48 AM -0800, "Maira Wenzel" <notifications@github.com<mailto:notifications@github.com>> wrote:


  1.  If it makes sense, I'm fine with that. But for example, the steps for Windows on the getting-started page is completely different from the topic.
  2.  I prefer something like "Lap around .NET" or "Key .NET Concepts". My 2 cents, of course!

I'll take a more closer look again at #175<https://github.com/dotnet/core-docs/pull/175> right now.

-

**Comment by mairaw** [comment]
It did work! Did you clean it up the e-mail to reply? Because when @stevehoag replied using the e-mail, all the rest of the earlier convo was there too.
Ah ok, I didn't know the main page was already updated to the new way. Sounds good!

**Comment by mairaw** [comment]
Never mind, the rest of the convo is there too when you expand the ...

**Comment by matthewreily** [comment]
Are we going to cover testing as a topic? I have not seen any mention of it and not sure if it is even within the scope of the core-docs.

**Comment by cartermp** [comment]
@matthewreily good question.  What I've been doing this far is incorporating Xunit into the relevant article(s).  I'm almost tempted to say that we could just link directly to the testing frameworks available.  I haven't used Nunit, but Xunit's documentation is really good, so I think we'd want to point people there if at all possible.

**Comment by matthewreily** [comment]
Sounds good to me and I agree that Xunit's documentation is really good.  I'll start incorporating it in as well where relevant.  Maybe we could start adding some unit tests to the samples we produce as well.  I think adding by adding some simple tests to our samples, we would help those wanting to learn how to get started.
