### ISSUE TITLE
Change repo header to point to the new site

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#177]
I couldn't find how to fix the header that is still pointing to RTD site on the main page of the repo: https://github.com/dotnet/core-docs

**Comment by BethMassi** [comment]
It looks correct to me: http://dotnet.github.io/docs/index.html

**Comment by mairaw** [comment]
It did have the wrong site yesterday but it does look correct today. I swear I'm not going crazy! :smile:
