### ISSUE TITLE
Need automated way to remove wrench icon when articles are merged

### ISSUE THREAD

**Issue by BethMassi** [dotnet/core-docs#187]
Currently there is no automated way on build of the docs to manage the removal of the wrench icon (which indicates that articles need to be written). This is going to cause additional headaches particularly with community contributions because now in addition to writing the article, you need to modify lines to remove the wrench in these places:

1.In the main TOC
2.In the sub-topic TOC (index.md)
3.In the article itself

cc @pengbian and @chenkennt

**Comment by BillWagner** [comment]
So, I thought the wrench was just a cool icon. I added it in my finished articles. Shows what I know.... :hankey:

**Comment by matthewreily** [comment]
Ha.  Same here @BillWagner

**Comment by BethMassi** [comment]
LOL. @blackdwarf is working on making the contribution guidelines clearer.

**Comment by cartermp** [comment]
Maybe we should prefix our favorite articles with a cool icon.  Or perhaps we can style Up for Grabs content with (☞ﾟヮﾟ)☞ _Article Here_?

**Comment by blackdwarf** [comment]
The wrench can be replaces with whatever, as long as it indicates that the article is in an unfinished state. The contrib guidelines are merged and there is a second PR waiting. Sorry about the confusion @BillWagner and @matthewreily.

**Comment by mairaw** [comment]
Not desired anymore. We need to open a new issue for a better TOC generation.
