### ISSUE TITLE
Word Order in Type Titles

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#193]
On the TOC content pages, in the h1 titles, the type names (Class, Struct, Interface, Enum and Delegate) are the first words. This is in contrast to the .NET Framework Class Library, where type names come last in the titles.

Examples:
https://dotnet.github.io/api/System.Action%601.html (“Delegate” is first word in title)
https://msdn.microsoft.com/en-us/library/018hxwa8(v=vs.110).aspx (“Delegate” is last word in title)

/cc @blackdwarf @chenkennt @pengbian

**Comment by mairaw** [comment]
This is fixed in docs: https://docs.microsoft.com/en-us/dotnet/core/api/system.action-1
