### ISSUE TITLE
Missing Space after Namespace: and Assembly:

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#195]
On the API pages, there is no space between Namespace and its value, and nor is there one between Assembly and its value.

**Example:**
https://dotnet.github.io/api/System.Action.html

**Current Appearance:**
Namespace:System
Assembly:System.Runtime.dll

**Suggested Appearance**
Namespace: System
Assembly: System.Runtime.dll

/cc @blackdwarf @chenkennt @pengbian

**Comment by mairaw** [comment]
This no longer applies with the move to docs.microsoft.com.
