### ISSUE TITLE
Improve TOC Sidebar Readability

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#197]
The entries in the TOC sidebar are stacked closely on top of one another, which makes them difficult to distinguish. Increasing vertical margins or padding could solve this.

**EXAMPLE:**
https://dotnet.github.io/api/
![toc-types-lacking-spacing](https://cloud.githubusercontent.com/assets/3714242/11672186/274f33a4-9dc3-11e5-8220-512b1ab3319f.JPG)

/cc @blackdwarf @chenkennt @pengbian

**Comment by blackdwarf** [comment]
Punting pending decision on the site and other things. The styles may be wholly different in the future.

**Comment by mairaw** [comment]
This is improved in docs:
![image](https://cloud.githubusercontent.com/assets/12971179/16778281/3086f0e2-4822-11e6-8d22-7f926d910fae.png)

Closing this issue.
