### ISSUE TITLE
Some Class Properties Missing Summaries and Descriptions

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#198]
On http://dotnet.github.io/api/, some classes have properties lacking summaries and descriptions. However, when I run a local version of the site, these summaries and descriptions have values, which are being taken from the .yml files in core-docs\api folder.

**Live Site:** 
Example:
System.Array.Collection.ICollection.IsSynchronized
http://dotnet.github.io/api/System.Array.html#System_Array_System_Collections_ICollection_IsSynchronized
![icollection-dot-issynchronized-is-missing-summary-and-description](https://cloud.githubusercontent.com/assets/3714242/11673938/5412a606-9dd1-11e5-9ec9-859ed4244125.JPG)

**Local Version of Site:**
Example:
![local-icollection-dot-issynchronized-has-summary-and-description](https://cloud.githubusercontent.com/assets/3714242/11673937/540fc292-9dd1-11e5-91d0-064d0219400e.JPG)

/cc @blackdwarf @chenkennt @pengbian

**Comment by chenkennt** [comment]
Seems the one on github.io (manually built by me) and the one you're using (built on our CI machine) are using different intellisense files. I'm using intellisense files of .NET 4.6 and our CI machine is using the ones of .NET 4.0. @blackdwarf which one do you think is the right one we should use?

**Comment by mairaw** [comment]
I think we should use the latest @chenkennt. .NET 4.6.1

**Comment by chenkennt** [comment]
Ok, but 4.6.1 doesn't have comments for some of the methods like Sean showed in the screenshot.

**Comment by mairaw** [comment]
I researched here a bit and it seems we lost these APIs when we moved from Dx to CAPS because they were PCL only and not framework APIs. Not sure if this was intentional or not.

**Comment by mairaw** [comment]
I think we have a different issue now. The EIIs (Explicit Interface Implementation) seem to be missing from docs: https://docs.microsoft.com/en-us/dotnet/core/api/system.array

System.Array should have ICollection.Count or IList.Add.

**Comment by bradygaster** [comment]
This has been repaired. See [here](https://docs.microsoft.com/en-us/dotnet/core/api/system.collections.icollection#System_Collections_ICollection_IsSynchronized)
