### ISSUE TITLE
docfx build is Generating a Warning

### ISSUE THREAD

**Issue by seandebutts** [dotnet/core-docs#200]
"docfx build" is building my site, but it also causes the following warning to be generated.

Warning: Too many missing definitions of xref, following is top 100:
        Microsoft.SqlServer.Server.SqlUserDefinedTypeAttribute            
 Microsoft.VisualBasic.CompilerServices.Operators.CompareObject(System.Object,System.Object,System.Boolean)
     Microsoft.Win32.RegistryKey.OpenRemoteBaseKey(Microsoft.Win32.RegistryHive,System.String)
        System.CodeDom
        System.Collections.BitArray.Count
        System.Threading.Thread.CurrentCulture
        System.Collections.IHashCodeProvider
        System.Web.DynamicData.DynamicControlParameter
        System.ComponentModel.Design.IComponentChangeService.ComponentChanged
        System.ComponentModel.Design.IComponentChangeService.ComponentChanging
        System.Console.WindowHeight
        System.Console.WindowTop
        System.Data.OleDb.OleDbCommand.ExecuteReader
        System.Data.OleDb.OleDbCommand
        System.Data.DataRow
        System.Data.Common.DbDataAdapter
        System.Data.IDataRecord.FieldCount
        System.Data.DataSet
        System.Data.Common.DbCommandBuilder
        System.Data.SqlClient.SqlConnection.ChangePassword(System.String,System.String)

The warning them goes on for many more lines.

**Comment by seandebutts** [comment]
Here is the full message, with info and warnings:

[full-docfx-build-info-and-warning.txt](https://github.com/dotnet/core-docs/files/58723/full-docfx-build-info-and-warning.txt)

**Comment by mairaw** [comment]
I don't think this is applicable anymore. Closing this issue.
