### ISSUE TITLE
Porting Docs - Overview, Tools, Libraries, and NuGet Packages First

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#212]
The current TOC for porting is organized like this:

- Overview
- Tooling
- Porting your applications
- Porting your libraries
- Porting your NuGet packages

There are common steps among all three, namely:

- Is it worth it to port?
- Figuring our your 3rd party dependencies and resolving incompatibilities (if possible)
- Figuring out your .NET Framework dependencies and resolving incompatibilities (if possible)
- Getting your project system at a state where you have a basis for compilation
- Forming a plan for the order with which things get ported over

"Porting your applications" is a much larger topic, as the API surface area for applications and services is typically far larger than that of libraries and NuGet packages.  The example I like to bring up is the [lack of any implementation](https://github.com/dotnet/corefx/tree/master/src/System.Security.Principal/src/System/Security/Principal) of `IPrincipal` on non-Windows platforms, which means that an application which does custom role-based authentication doesn't really have a strong reason to move over to .NET Core, because you can't deploy to anything *other* than Windows anyways (well, unless you want to write the code that actually implements RBAC on your OS of choice).

Because of that, I'm thinking that putting porting apps on the sideline for now is a good idea.

**Comment by blackdwarf** [comment]
@cartermp agreed.

**Comment by blackdwarf** [comment]
@cartermp is this done? If yes, close pls.

**Comment by cartermp** [comment]
Not yet, but yeah I'll close once the PR gets merged.

**Comment by ghogen** [comment]
Superceded by the above issues.
