### ISSUE TITLE
Porting .NET MSDN docs to Core - Base Types

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#217]
We need to port the relevant content from MSDN that applies to .NET Core.

The base types docs are still applicable to .NET Core. This is the starting point for base types:
https://msdn.microsoft.com/en-us/library/7wchwf6k(v=vs.110).aspx

**Comment by mairaw** [comment]
@stevehoag is this what the current active PR from you is for? if so, we should add the Fixes to the description to link the two.

**Comment by stevehoag** [comment]
Yes... done.
