### ISSUE TITLE
Porting .NET MSDN docs to Core - Collections and Data Structures

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#218]
We need to port the relevant content from MSDN that applies to .NET Core.

The collections docs are still applicable to .NET Core. This is the starting point for collections:
https://msdn.microsoft.com/en-us/library/7y3x785f(v=vs.110).aspx

**Comment by ghogen** [comment]
need some info for \\BUILD on collections

**Comment by stevehoag** [comment]
Topics written #372 #373 #374 #375 #376 #377 #378 #379 #380 #381 #382 #383 #384
