### ISSUE TITLE
Porting .NET MSDN docs to Core - Numerics

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#220]
We need to port the relevant content from MSDN that applies to .NET Core.

The generics docs are still applicable to .NET Core. This is the starting point for numerics:
https://msdn.microsoft.com/en-us/library/dn879696(v=vs.110).aspx

**Comment by stevehoag** [comment]
Starting work on this one

**Comment by stevehoag** [comment]
Completed #400
