### ISSUE TITLE
Porting .NET MSDN docs to Core - Exceptions

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#222]
We need to port the relevant content from MSDN that applies to .NET Core.

The exceptions docs are still applicable to .NET Core. This is the starting point for exceptions:
https://msdn.microsoft.com/en-us/library/5b2yeyab(v=vs.110).aspx

**Comment by kempb** [comment]
I've completed ported the Exceptions topics over to GitHub. I just need to review the contents online to be sure they look and work okay.

**Comment by mairaw** [comment]
Just need to review one last sample

**Comment by kempb** [comment]
All topic are now done except for the topic "Using User-Filtered Exception Handlers", which is being tracked separately in issue #367 .
