### ISSUE TITLE
Porting .NET MSDN docs to Core - Common Language Runtime

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#227]
We need to port the relevant content from MSDN that applies to .NET Core.

The Common Language Runtime doc is still applicable to .NET Core. This is the topic:
https://msdn.microsoft.com/en-us/library/8bs2ecf4(v=vs.110).aspx

**Comment by ghogen** [comment]
Just need a brief summary here for build.

**Comment by stevehoag** [comment]
Completed #411
