### ISSUE TITLE
Porting .NET MSDN docs to Core - Automatic Memory Management

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#228]
We need to port the relevant content from MSDN that applies to .NET Core.

The Automatic Memory Management doc is still applicable to .NET Core. This is the topic:
https://msdn.microsoft.com/en-us/library/f144e03t(v=vs.110).aspx

There's also this section on GC: https://msdn.microsoft.com/en-us/library/hh156531(v=vs.110).aspx

**Comment by BillWagner** [comment]
closed in PR #975
