### ISSUE TITLE
Porting .NET MSDN docs to Core - Language Independence

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#230]
We need to port the relevant content from MSDN that applies to .NET Core.

The language independence doc is still applicable to .NET Core. This is the topic:
https://msdn.microsoft.com/en-us/library/12a7a7h3(v=vs.110).aspx

**Comment by ghogen** [comment]
For Build include summary not full topic.

**Comment by stevehoag** [comment]
Content ported; #392

**Comment by stevehoag** [comment]
Fixed in #981
