### ISSUE TITLE
Improve the .NET Core topic on MSDN

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#232]
The topic about .NET Core on MSDN hasn't been updated in a long time and needs to be reviewed:
https://msdn.microsoft.com/en-us/library(d=lightweight)/dn878908(l=en-us,v=VS.110).aspx

**Comment by stevehoag** [comment]
@mairaw Didn't you already update this topic? Can we close this?

**Comment by mairaw** [comment]
Nope, I had to work on some other priorities so didn't get to finish this one.

**Comment by mairaw** [comment]
I've published a new version today. Let me know if you have any feedback on that topic. But I'm closing this one for now.
