### ISSUE TITLE
Update New Libraries Doc for RC2

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#248]
- [x] Get rid of DNX stuff
- [x] Update TFMs to use what's shipping for RC2
- [x] Put a blurb in which clarifies what it means to target .NET as a whole (and reiterate that point for .NET Core)
- [x] Update the Multiple Projects section and expound upon when `gobal.json` is necessary
- [x] Update testing to use the `dotnet` commands with any relevant changes needed
- [x] Update examples to use packages outside of `NETStandard.Library`
- [x] Mention that targeting `Microsoft.NETCore.App` is a useful scenario if you want larger API surface area
- [x] Package trimming with a how-to and example
- [x] Updated samples

/cc @richlander @blackdwarf

**Comment by cartermp** [comment]
tag #545 to remember to collapse the table

**Comment by mairaw** [comment]
Are you done with this one @cartermp?

**Comment by cartermp** [comment]
Yup!
