### ISSUE TITLE
Reference for project.json/global.json

### ISSUE THREAD

**Issue by aL3891** [dotnet/core-docs#256]
Continuing from dotnet/cli#1276 about reference docs for project.json/global json. Are you interested in contributions for this? I've been looking at the code just for my own understanding so i might as well write it down.

Questions from the other issue, 
Is someone already working on this? 
where should i put those docs? (just under docs/cli?)

cc @blackdwarf

**Comment by shahid-pk** [comment]
:+1:  would love to see this, although i don't need them , but whenever i come across people that are coming from non .net backgrounds they want to try docs from github.io site which are not in very good state for beginners.

**Comment by cartermp** [comment]
This is something I've been thinking about as well.

We'll need to figure out a good place for them.  `project.json` is broader in scope than just the CLI, as you may end up having to hand-author your own sections in Visual Studio for multitargeting and other configuration.

If you're up for it, I'd love to see an outline of what you're thinking.

For reference, there's older material available [here](https://github.com/aspnet/Home/wiki/Project.json-file), [here](http://aspnet.readthedocs.org/en/latest/dnx/projects.html), and the schema for `project.json` is [here](http://json.schemastore.org/project).

**Comment by blackdwarf** [comment]
@cartermp `project.json` is foundational .NET Core concept, whether you hand-author your own sections or not is besides the point. We need to have a place where the schema is explained, together with its indeded use, tools and whatnot. However, there are some docs over at docs.asp.net that talk about it. 

@danroth27 what are your thoughts?

**Comment by danroth27** [comment]
All of the DNX related docs on docs.asp.net will be removed once we ship the first preview of ASP.NET Core on .NET Core. I would expect project.json and global.json to be fully documented with the .NET Core docs.

**Comment by cartermp** [comment]
@blackdwarf I see two different angles that need to be explored - a scenario-driven approach and a reference approach.  The page in the asp.net docs I linked to does a great job with being scenario-driven and it's something we can adapt to the particular angle we feel is best.  I wasn't able to find any reference material, so that could end up being a pretty big effort.

**Comment by aL3891** [comment]
i agree that the project.json stuff is broader than the cli, maybe it should be its own section called ".Net core project model" or something like that, and under there you'd have the reference docs (basically the schema but a little friendlier) and the conceptual docs. I imagine those could be pretty much lifted of the asp.net docs and just tweaked.

**Comment by blackdwarf** [comment]
@danroth27 thanks, we're on the same page! :)

@cartermp there are reference materials in the ASP.NET repos, not the docs. So you can start from that.

**Comment by aL3891** [comment]
@blackdwarf so should i take a look at this, or leave it to @cartermp? :)

**Comment by cartermp** [comment]
@aL3891 We'll have to figure out a good outline of what the articles would look like and agree on the particular angle each one would take.  I'm happy to work with you and figure out a good approach here if you still would like to contribute.

**Comment by blackdwarf** [comment]
@aL3891 this is open source, so go for it! :)

**Comment by aL3891** [comment]
Sure, no problem!
how about having an article separate from cli called "project model" with an overview, reference of the attributes in the project.json/global.json and some how to scenarios? As we've mentioned, the overview and scenarios can probably partially be lifted from the dnx docs.

**Comment by mairaw** [comment]
We can close this one, no?

**Comment by cartermp** [comment]
Yup!

**Comment by BillWagner** [comment]
Awesome. Closing now.
