### ISSUE TITLE
[Style] Shoud we include the author on each article?

### ISSUE THREAD

**Issue by aL3891** [dotnet/core-docs#258]
I've started working on the docs for the .net core project system and as i pull docs from different places i find myself hesitating because i feel like i'm stealing other peoples work and putting my name on it.

Also, looking further down the line, if more people collaborate on an article, should all of them be mentioned as authors? if i make a small edit on some document, does that make me an author?

I think it would be better to not have the author on every page (as per the current style guide) but instead perhaps have a collaborators page or something, similar to a wiki. That would make it easier for people to make small changes without feeling they are changing the work of "someone else".

What is your opinion on this?

**Comment by cartermp** [comment]
I was thinking about this as well.  Currently we've been just having the original author put their name under the title.  Two main authors could be fine I suppose.  The question of contributors for smaller things (e.g. fixing spelling/grammar, or adding a small paragraph) is interesting.  I'd personally go with a list of contributors at the end of each article, but there's a number of ways to do it.

Thoughts, @blackdwarf ?

**Comment by BillWagner** [comment]
We should also figure out how to make the attributions when the new .NET core article is an update of previous .NET framework documentation. Those tasks feel more like an update or an edit rather than original content.

**Comment by aL3891** [comment]
One option would be to credit "msdn" as an author, i don't know how they've worked in the past with the msdn docs, but I've never seen any author information there.

I don't know though, as much as i'd like to leave my name on each page, wont that be cluttered over time? We could just have a contributors page or something.

**Comment by blackdwarf** [comment]
Hm, don't we already have an author specified per article? Usually, the articles' authors are all listed if they are co-authors, so we should follow that logic. 

Edits and minor spell-checks should not be of same gravity as the authorship; indeed, in general in publications they are not, as far as I know. We *could* have a separate section for them, but that seems...dunno. Maybe an attribution page separately for all the people that have kept our grammar/spelling in check?

For MSDN, it is interesting...all of the MSDN articles actually **do** have an author, so if it the same person doing the update, it is easy. If it is not, the question becomes how much of an update is it. 

@mairaw what are you thoughts on MSDN?

**Comment by stevehoag** [comment]
Although MSDN articles do have an author, in most cases we don't know who that was - we only know the current owner.

**Comment by blackdwarf** [comment]
@stevehoag so that owner will be the person most likely to update the topic, if it is updated, for .NET Core, right?

**Comment by stevehoag** [comment]
Not necessarily - Ron and Maira own the topics, but we'll all be helping with the porting to .NET Core. Personally I wouldn't want to be considered an "expert" on a topic just because I ported it, so I don't think attributing an author on these topics is appropriate.

**Comment by mairaw** [comment]
And I just inherited mine. :smile: 

Missed this convo while I was out. 
I agree with you @stevehoag. I don't think we have to add the authors to the ones we're porting. I just talked to @rickandmsft to understand how they're doing for asp.net. They add the original author's name in the byline. Then if someone makes significant edits, they can add their name too.

**Comment by Rick-Anderson** [comment]
We (docs.asp.net) feel that having an author is important. It gives the doc a personal touch and makes it less of the bit buck MSDN has become. It's also a way for internal MS folks outside your division to contact you. We've found internal feedback pretty valuable, as MS employees are generally very sharp.  Even if you just ported the doc, if someone internal contacts you, you can generally refer them to the expert.
If I had my way there would be a Contributors section at the end of the doc. The most important item  to prevent MSDN bit buck syndrome (aka no one is listening) is to have DISQUS or another mechanism for customers to leave feedback.

**Comment by aL3891** [comment]
I agree the about the no listening thing on msdn, but i think that's also mitigated by the docs being open source and accepting pull requests. I still think having the author as prominently as they are now makes contributing to the docs more a process of asking the author to change their work rather than creating a living document that is owned by the community. 

Also, years down the line, the original author might have moved on to other things, and while they are probably still an expert they might not be able (or want) to respond as fast as the general community via say, a github issue.

There is a difference though between something like an article on a specific topic or something like a programming guide or a reference doc.

**Comment by ghogen** [comment]
The azure.com model has a main author and a list of contributors -- that way there's someone definite who should be on the hook for monitoring the topic, but a lot of other people are acknowledged as well.  The main author is not necessarily the same person who wrote the topic, since people change roles and a new "owner" takes over.  However, they would be the person most in touch with the area at any given time and should be able to address concerns and questions.

**Comment by Rick-Anderson** [comment]
@aL3891 try weeks down the line. In the last 6 months we've had 3 authors move. Yes, open source solves many evils, it's easy for customers to open an issue (even easier than a PR).

**Comment by BillWagner** [comment]
I think this can be closed. The build system grabs the author and any contributors from the repo history and metadata.

/cc @bradygaster If I'm correct, go ahead and close.

**Comment by cartermp** [comment]
Yep, let's close it out.  We've got the info now.
