### ISSUE TITLE
What is the .NET Platform?

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#280]
Issue tracking new topic at http://dotnet.github.io/docs/getting-started/what-is-dotnet.html

**Comment by cartermp** [comment]
Hah, yeah this seems like an important one to get written for //Build :smile:

**Comment by mairaw** [comment]
You think? :smile:

**Comment by blackdwarf** [comment]
This is not super important.

**Comment by mairaw** [comment]
Some reference for this work: https://github.com/dotnet/corefx/tree/master/Documentation/architecture
