### ISSUE TITLE
Development using Visual Studio Code

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#282]
Issue tracking new topic at http://dotnet.github.io/docs/getting-started/devenv/using-visual-studio-code.html

**Comment by cqcallaw** [comment]
I'd love to contribute what I know about this topic, although it might not be comprehensive: my experience is with C# only.

**Comment by BillWagner** [comment]
@cqcallaw Are you still interested in helping out? I will be starting on this shortly, and I'm happy to collaborate.

**Comment by cqcallaw** [comment]
@BillWagner I'd love to help out, but the [contribution procedure](https://github.com/dotnet/core-docs/blob/master/CONTRIBUTING.md#process-for-contributing) lead me to believe some sort of approval had to be given first, which I was assuming must come from @mairaw.

**Comment by BillWagner** [comment]
Well, there's already an issue created, so it's work that should happen. 

I'll checkin with @mairaw and see what else has to happen. With time zone differences, it will be sometime tomorrow afternoon (EDT) when I hear back.

**Comment by mairaw** [comment]
Sorry I missed your comment earlier @cqcallaw. I just created the issues based on what we had on the TOC at the time. Feel free to work with @BillWagner on this one.

**Comment by cqcallaw** [comment]
@mairaw No worries, thanks for the the confirmation!

@BillWagner Not exactly sure how you wanted to collaborate, but I thought I'd get the ball rolling with the kernel of the documentation: https://github.com/cqcallaw/core-docs/blob/vs-code-setup/docs/getting-started/devenv/using-visual-studio-code.md

**Comment by BillWagner** [comment]
@cqcallaw That's a great start. For the finished content, we're shooting for something that's parallel to the Visual Studio guide in this PR #410, in addition to the setup content you're creating.

I'll start working on the "golden path" part. I created a branch here: https://github.com/BillWagner/core-docs/tree/vs-code-golden-path

I added yours to my watch list. We can keep in sync and link across content.

One quick note: You should add your byline on the article you're writing. We appreciate the contributions, and want to recognize it. Most people have been using their name, and a link to their GitHub profile.

**Comment by tsolarin** [comment]
Is there still a chance to contribute to this?

/cc @BillWagner

**Comment by BillWagner** [comment]
Yes there is. Check out the two branches referenced above. @cqcallaw is working on setting up the environment and getting tools in place. I've got one that will create a sample, run it, and use the debugging tools. (Not much there yet; I'm happy to have help.

**Comment by tsolarin** [comment]
Would love to help out with the sample, how do I get started? @BillWagner

**Comment by tsolarin** [comment]
I'll start working on my fork using your template here: https://github.com/BillWagner/core-docs/blob/vs-code-golden-path/docs/tutorials-samples/vs-code-golden-path.md. Is that approach suitable? @BillWagner

**Comment by BillWagner** [comment]
@tsolarin That would be great. I'll start filing in code in a sample for the application.

**Comment by tsolarin** [comment]
Here is my branch: https://github.com/tsolarin/core-docs/blob/vs-code-golden-path/docs/tutorials-samples/vs-code-golden-path.md. So you can track progress.
/cc @BillWagner

**Comment by cqcallaw** [comment]
@tsolarin @BillWagner thanks for continuing to push this forward. I haven't found as much time as I'd like to work on this, so I don't think I'll be able to continue contributing. Please feel free to use any of the content I've already generated.

**Comment by tsolarin** [comment]
No problem @cqcallaw. @BillWagner I've already made some updates to my branch, I'm aiming to complete it by the end of this week so while you're reviewing it I could pick up where @cqcallaw left off

**Comment by BillWagner** [comment]
@tsolarin I looked over what you've completed so far. It's a good start. As you keep working, I'd like to see more of an emphasis on *why* readers should perform any of the steps you mention: Explain to readers why to create a global.json. Explain why to use the 'src' and 'test' directories for different projects. 

As you go through every step, help the reader understand why they should be taking these actions. That will help them understand the process. They'll be able to extend what you've shown them to their own projects and their own work.

Let me know if that makes sense.

Also, it looks like you haven't had time to update this in a little more than a week. Let me know if you still have time to finish this up, or of other demands have taken your time.

**Comment by tsolarin** [comment]
HI @BillWagner thanks for taking a look, I'll get to incorporating your feedback ASAP. Let's just say I've kinda been waiting for someone to take a look at it so I could have an idea of how to proceed, I can definitely finish it up

**Comment by BillWagner** [comment]
@tsolarin Sounds good. Just add a note here and '@' mention me and I'll look again.

**Comment by tsolarin** [comment]
@BillWagner I've made some considerable updates to my branch. Do take a look

**Comment by BillWagner** [comment]
@tsolarin I saw the previous versions.  I'll pull that into my branch, and update my PR.

Then, I think once we get reviews, this can get merged.

In the meantime, if you submit a .NET Foundation CLA, it will be make the merge happen faster: https://cla2.dotnetfoundation.org

Thanks again for contributing.

**Comment by tsolarin** [comment]
@BillWagner I've signed the agreement. I'll take a look at more content I can help out with, thanks for the opportunity
