### ISSUE TITLE
Development using Sublime Text

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#284]
Issue tracking new topic at http://dotnet.github.io/docs/getting-started/devenv/using-sublime.html

**Comment by blackdwarf** [comment]
@richlander you want to take this?

**Comment by mairaw** [comment]
Same as the vim question. Do we still want a topic for this @blackdwarf?

**Comment by blackdwarf** [comment]
@mairaw same as the vim answer.

**Comment by mairaw** [comment]
:smile:
