### ISSUE TITLE
Writing Console Apps: Creating single binaries with native compilation

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#289]
Issue tracking new topic at http://dotnet.github.io/docs/console/single-binaries.html

**Comment by blackdwarf** [comment]
This needs to be removed from the TOC.

**Comment by cartermp** [comment]
Would it be added back in later?  I would think that we'd still be interested in the notion of creating single binaries at some point.

**Comment by blackdwarf** [comment]
@cartermp no, we will never add it back. It is dead. It has gone to meet its maker. If we didn't nail it to GitHub, it would be pushing up the daisies. It has put down the curtain and gone to meet the choir invisible. It is a dead topic. 

https://www.youtube.com/watch?v=npjOSLCR2hE :)))

Of course we will put it back.

**Comment by mairaw** [comment]
Closing this for now. We just need to link to the native compilation roadmap from our core/index.md file when that is published.
