### ISSUE TITLE
Package management: Working with Nuget Packages

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#291]
Issue tracking new topic at http://dotnet.github.io/docs/packaging/working-with-nuget-packages.html

**Comment by blackdwarf** [comment]
Same, so can we just link to http://docs.nuget.org/? The only special thing would/could be the versions.

**Comment by ghogen** [comment]
So we just agreed to have this one topic, including the lilnk to nuget docs. Other Nuget work items can be postponed (post Build).

**Comment by tdykstra** [comment]
Closing this issue, will use #306 to track the overall NuGet doc mentioned in #306.
