### ISSUE TITLE
Packaging and deploying apps: Deploying to a shared runtime

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#295]
Issue tracking new topic at http://dotnet.github.io/docs/deployment/shared-runtime.html

**Comment by stevehoag** [comment]
@rpetrusha Didn't this get rolled into the Deployment Concepts topic? Close?

**Comment by rpetrusha** [comment]
Yes, it did. To [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index)
