### ISSUE TITLE
Packaging and deploying apps: Deploying self-contained applications

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#296]
Issue tracking new topic at http://dotnet.github.io/docs/deployment/self-contained-apps.html

**Comment by stevehoag** [comment]
@rpetrusha Is this covered by the Deployment Concepts topic?

**Comment by rpetrusha** [comment]
Yes. It's covered by [.NET Core Application Deployment](https://docs.microsoft.com/en-us/dotnet/articles/core/deploying/index).
