### ISSUE TITLE
Packaging and deploying apps: Deploying single binaries

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#297]
Issue tracking new topic at http://dotnet.github.io/docs/deployment/single-binaries.html

**Comment by ghogen** [comment]
remove this from the TOC

**Comment by stevehoag** [comment]
@rpetrusha Is this covered by the Deployment Concepts topic?

**Comment by blackdwarf** [comment]
@stevehoag nope, but we will not be documenting this since the feature is not baked yet. Closing.
