### ISSUE TITLE
Porting apps: Overview of porting process

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#300]
Issue tracking new topic at http://dotnet.github.io/docs/porting/overview.html

**Comment by cartermp** [comment]
Although I was tracking an existing PR with #212, I think I'm going to break that up until multiple PRs and track with these issues.

The overview doc will go over:

1. Should you port?

   a. Advantages that .NET Core brings
   b. Good candidates for porting
   c. Bad candidates for porting

2. Porting process overview as a list of steps:

   a. Handle 3rd party dependencies, NuGet and non-NuGet
   b. Migrate existing assets to .NET Framework 4.6.1 if you haven't already
   c. Analyze .NET Framework APIs you use and develop a plan of attack
   d. Port tests over to xUnit or NUnit, as MSTest does not support .NET Core
   e. Execute your plan of attack

3. Overview of tools you'll use

   a. ApiPort - command line or VS extension
   b. NuGet - command line or NuGet Package Explorer
   c. .NET CLI - the low-level toolset that VS uses under the covers to build/restore/etc

**Comment by ghogen** [comment]
Ron can help with this.
