### ISSUE TITLE
Porting apps: Porting your applications and services

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#301]
Issue tracking new topic at http://dotnet.github.io/docs/porting/applications.html

**Comment by ghogen** [comment]
General guidance.
Include info on what types of apps you can and cannot port. e.g. WPF, Web Forms, etc.

**Comment by cartermp** [comment]
The issue I'm having with this doc is that porting an app is, depending on the app, orders of magnitude more challenging than libraries.  There are many, many things .NET Core simply lacks support for that are complete non-starters for apps.  If I were to list out things that you can't port, it would be a really long list.

The most obvious candidate here is web apps, for which we can link to ASP.NET docs.  Console apps can be ported as well, but there really isn't much to state here that's specific to them.

I think that content from the libraries doc can mostly be ported here, modified to have the correct `project.json` incantations

**Comment by mairaw** [comment]
This is more of an ASP.NET scenario and is covered in their docs.
