### ISSUE TITLE
Porting apps: Porting your libraries

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#302]
Issue tracking new topic at http://dotnet.github.io/docs/porting/libraries.html

**Comment by ghogen** [comment]
same content as #301

**Comment by cartermp** [comment]
Although I was tracking an existing PR with #212, I think I'm going to break that up until multiple PRs and track with these issues.

Here's what I'm thinking:

1. Prerequisites
2. Getting 3rd party dependencies in order

   a. When using NuGet, what folders to look for
   b. When not using NuGet, use ApiPort (this will involve jumping around the article a bit)
   c. Recommendations for when your 3rd party dependencies don't run on .NET Core

3. If applicable, porting to .NET Framework 4.6.1

   a. Using ApiPort and analyzing the results
   b. If there are any incompatibilities, recommendations for fixing (this is pretty unlikely)
   c. How to upgrade to next version in VS

4. Using ApiPort to analyze .NET Framework 4.6.1 ---> .NET Core

   a. Using ApiPort
   b. Guidelines for dealing with incompatible APIs used
   c. Guidelines for a plan of attack if you think you can move forward

5. Before you deal with code: .NET Core project model, project system in VS, `netstandard`

   a. Quick overview of the project model and `project.json`, which is going to be the center of things as far as building and dependencies are concerned (link to further docs)
   b. How best to pick between xproj and csproj
   c. Understanding what `netstandard` version to use and how this is influenced by your 3rd party dependencies and .NET Framework APIs used.  (Link to further docs on `netstandard`)

6. If applicable, getting your tests ported over

   a. If using xUnit, how to set that up and run tests
   b. If using NUnit, how to set that up and run tests

7. Getting your project to the point where all you need to deal with is your own code

   a. Based on your needs, pick the correct project type in VS and the correct `netstandard` version
   b. Entering the correct `project.json` incantations so everything works
   c. Referencing this project in the relevant test project(s)
   d. Copy code over, work out compile errors, run tests, repeat!

8. Getting the library up on nuget.org?

   Link to the next article, which is getting a .NET Core library into a NuGet package that can then be distributed via NuGet.

/cc @terrajobst @richlander

**Comment by BillWagner** [comment]
@cartermp Can we close this issue? It looks like all but the NuGet PR is merged or closed.
And, I'd like to track the NuGet PR on a different milestone (this is the only issue not completed for the //build milestone)

**Comment by cartermp** [comment]
Yep, good to close!
