### ISSUE TITLE
.NET Command Line Interface Reference

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#304]
Issue tracking new topic at http://dotnet.github.io/docs/cli/index.html

**Comment by mairaw** [comment]
This one doesn't have a wrench but I thought we should add an issue for it

**Comment by aL3891** [comment]
There are some reference docs over in the cli repo, should they be moved here?

**Comment by blackdwarf** [comment]
@aL3891 yes, that is the idea with some "meat" around it.

**Comment by stevehoag** [comment]
Referenced topic no longer exists - closing.
