### ISSUE TITLE
The API reference for value types is empty

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#308]
The API reference pages for all value types seem to be empty. This includes primitives ([`Int32`](http://dotnet.github.io/api/System.Int32.html)), `struct`s ([`DateTime`](http://dotnet.github.io/api/System.DateTime.html)) and `enum`s ([`DayOfWeek`](http://dotnet.github.io/api/System.DayOfWeek.html)).

**Comment by mairaw** [comment]
@blackdwarf something happened with this build. Lot of pages are empty including some I'm sure had content before, even if it was just the API skeleton.

Thanks for catching this @svick.

**Comment by blackdwarf** [comment]
@chenkennt can you take a look? I don't have access to the build server.

**Comment by chenkennt** [comment]
It's fixed.
