### ISSUE TITLE
.NET Core CLI conceptual & scenario documentation

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/core-docs#317]
This issue tracks working on conceptual documentation. Cross-tracked in the CLI repo on dotnet/cli#1760.

- [x] Conceptual docs
  - [x] CLI Overview
  - [x] Migrating to CLI from DNX
  - [x] CLI App Types [Standalone vs. Portable]
  - [x] RID & TFM Catalogue

**Comment by cartermp** [comment]
This may not be the angle you want to take for CLI ---> DNX, but [this gist](https://gist.github.com/cartermp/80a2d4b2d5718b76eaa3) I was helping some of our customer engagement with may be a starting point.

**Comment by stevehoag** [comment]
@blackdwarf Is this something that still needs to be tracked?

**Comment by blackdwarf** [comment]
This is actually done.
