### ISSUE TITLE
System.Runtime.Serialization doesn't exist in .NET Core, but is documented

### ISSUE THREAD

**Issue by tangentsoft** [dotnet/core-docs#319]
According to [a Microsoft blog post](https://blogs.msdn.microsoft.com/dotnet/2016/02/10/porting-to-net-core/), binary serialization was purposefully removed from .NET Core, yet the namespace for it is [still documented](http://dotnet.github.io/api/System.Runtime.Serialization.html).

If you attempt to reference `System.Runtime.Serialization` from a .NET Core project, you get an error:

    .../Mono/Options.cs(137,22): error CS0234: The
    type or namespace name 'Serialization' does not exist in the namespace
    'System.Runtime' (are you missing an assembly reference?)

This is true even if you give this in the `dependencies` section for your framework reference in the `project.json` file:

    "System.Runtime": "4.1.0-rc2-23811"

**Comment by svick** [comment]
Binary serialization was removed, but the types listed are still included. According to [package search](https://packagesearch.azurewebsites.net/?q=System.Runtime.Serialization), a lot of the types are in the `System.Runtime.Serialization.Primitives` package. And after adding `"System.Runtime.Serialization.Primitives": "4.1.0-beta-23516"` to `dependencies` in `project.json`, `using System.Runtime.Serialization;` compiles fine for me.

**Comment by cartermp** [comment]
Yup, that namespace still has types that are valid for .NET Core.  Closing this out as it seems like @svick  has the fix for your particular issue.
