### ISSUE TITLE
Article TOC not useful if there are many sections

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#321]
For articles that have very large number of sections, the right-sidebar TOC is not very useful, because it's not scrollable. This is problematic especially since such articles are exactly ones where the TOC would be the most useful.

This happens for example in API reference for types with many members, like [`TypeInfo`](http://dotnet.github.io/api/System.Reflection.TypeInfo.html#properties). There, the properties I can see in the TOC (at my screen resolution) start with `Assembly` and end with `IsGenericType`. But anything beyond that cannot be seen in the TOC.

**Comment by cartermp** [comment]
Yes, I've ran into this as well - the right-hand TOC definitely needs to be scrollable.  @blackdwarf @chenkennt is this something we've looked at?

**Comment by blackdwarf** [comment]
@cartermp didn't notice it so far. This is def. something we would want fixed in the future.

**Comment by svick** [comment]
This seems to have been fixed by dotnet/docfx@86b84d3.
