### ISSUE TITLE
API Reference: Enum values show null rather than their numeric values

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#326]
See: http://dotnet.github.io/api/System.Xml.ReadState.html

`Closed` should be `4`, and so on.

/cc @chenkennt

**Comment by mairaw** [comment]
Maybe enumeration fields should be displayed on a table similar to MSDN? https://msdn.microsoft.com/en-us/library/fxtcxd31(v=vs.110).aspx

**Comment by cartermp** [comment]
@mairaw I like that.  Could be worth exploring.

**Comment by mairaw** [comment]
@cartermp can this be closed?
See how it renders on docs: https://docs.microsoft.com/en-us/dotnet/core/api/system.xml.readstate

**Comment by cartermp** [comment]
Yep.  I still think it's rendered a bit odd (not perfectly aligned), but it's no longer displaying misleading information.

**Comment by mairaw** [comment]
Yeah, I thought so too. I'll reactivate my feature request which has a Completed status so they continue to work on that.
