### ISSUE TITLE
Project Model Conceptual Overview

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#328]
We need to have a conceptual overview of the .NET Core project model.  It should include:

- What it is and what the relevant concepts are
   - Shared runtime and framework
   - Self-contained and Runtime Id (RID) interplay
   - Rationalizing the above
- What the relevant files are and overview of their purposes, with links to their respective references
- How it all works both in a CLI world and Visual Studio
- Examples of different ways to configure a project for various scenarios

The scenarios covered should include:

- Console Apps
   - Shared Framework
   - Self-contained
- Class Libraries
- ASP.NET Web Apps
- UWP Apps

/cc @blackdwarf @ghogen @rpetrusha @aL3891

**Comment by aL3891** [comment]
Ah, i was going to ask, but will the uwp tool chain also move to the dotnet cli then?

**Comment by cartermp** [comment]
Good question.  @blackdwarf do you know?

But either way, it still uses the `project.json` project model and has the `uap10*` TFM.

**Comment by aL3891** [comment]
Right but is it _the same_ project.json project model or is it slightly different? will uwp apps support `tools` for example? Its not a blocking issue for the docs but it will be a point of confusion for users i think.

**Comment by blackdwarf** [comment]
@cartermp I have no idea...

**Comment by cartermp** [comment]
Closing given the change in direction for the project system.  Will re-open if appropriate.
