### ISSUE TITLE
Do we still need the primer?

### ISSUE THREAD

**Issue by blackdwarf** [dotnet/core-docs#334]
Simple question: do we still need the primer, do we want it or should we remove it?

/cc @mairaw @cartermp @richlander

**Comment by cartermp** [comment]
I'm a little on the fence.  Although I generally think that less is more, the [Ceylong Language](http://ceylon-lang.org/documentation/introduction/) pulled this style of introduction rather well.  I think we need to decide what we want to go into "What is the .NET Platform" before we make any changes to the primer.

**Comment by blackdwarf** [comment]
@cartermp sure, but the "What is the .NET Platform" is going to be an overview, correct? Primer is more on the lvl200 side.

**Comment by blackdwarf** [comment]
Actually, come to think of it, we should leave the primer in. Whatever the "What is" article does, a little more detailed introduction into the various capabilities would be good. This should be really a primer, as in, a thing that offers just a glimpse. We should probably remove some sections from it, like dynamic data and whatnot. I will actually take care of that.

@mairaw @cartermp thoughts?

**Comment by cartermp** [comment]
:+1:

**Comment by mairaw** [comment]
Sounds good.

**Comment by blackdwarf** [comment]
This is done with #339 .
