### ISSUE TITLE
Porting .NET MSDN docs to Core - Exceptions - Using User-Filtered Exception Handlers

### ISSUE THREAD

**Issue by kempb** [dotnet/core-docs#367]
This topic was written to target VB only, and VB isn't currently supported in .NET Core. Unfortunately, the code was written using VB-specific elements for .NET Framework, so the code examples need to be rewritten so they'll work in C# on .NET Core. I have a new set of examples nearly complete, but they won't be ready before the //Build deadline. 
Therefore, I'm creating this tracking issue to cover creating new examples for this topic, post-//Build. When it's done, I'll re-add the topic to the exceptions docs.

**Comment by stevehoag** [comment]
Content was completed a while ago...
