### ISSUE TITLE
Invalid link on support page

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#390]
[The support page, in section Community meetings/meetups](http://dotnet.github.io/support/#community-meetingsmeetups) contains a link to "list of .NET meetup groups on Twitter", which points to https://twitter.com/DotNet/dotnet-user-groups. But that page does not exist.

**Comment by mairaw** [comment]
@terrajobst do you know what is the right URL if we still have this?

**Comment by mairaw** [comment]
@blackdwarf can we remove that link?

**Comment by svick** [comment]
It seems the link was fixed, it now points to https://twitter.com/dotnet/lists/net-user-groups, which works.
