### ISSUE TITLE
Outdated Linux instructions?

### ISSUE THREAD

**Issue by mwilliamson** [dotnet/core-docs#398]
The page "Installing .NET Core on Linux" at the URL http://dotnet.github.io/docs/getting-started/installing/installing-core-linux.html is still up, but so far as I can tell has been replaced by the URL https://dotnet.github.io/docs/getting-started/installing/installing-core-ubuntu.html. The former also doesn't seem to be in the repository. Am I right in thinking that those instructions should be considered outdated?

**Comment by mairaw** [comment]
@blackdwarf can @mwilliamson use the instructions on http://dotnet.github.io/getting-started for a Linux install?

**Comment by blackdwarf** [comment]
@mwilliamson sorry, which instructions are you referring to? The ones on the Getting Started page are most surely up-to-date.

**Comment by mairaw** [comment]
@blackdwarf he's talking about an article in the repo: http://dotnet.github.io/docs/getting-started/installing/installing-core-linux.html

**Comment by blackdwarf** [comment]
@mairaw ahhhhh...yeah, this should be removed, this page.

**Comment by mairaw** [comment]
@blackdwarf how do we do that since that file is not in the repo?

**Comment by blackdwarf** [comment]
Wait...if its not in the repo, how is it then getting built?

**Comment by mairaw** [comment]
No clue. Maybe a bug with docfx? You seem to have renamed that file in January but somehow the old built html one wasn't removed from the build.

/cc @chenkennt

**Comment by blackdwarf** [comment]
Hmm...renamed it...so the build server must have not cleaned before re-build.

**Comment by chenkennt** [comment]
Seems to be a bug in build server, @MarzinZ to take a look.

**Comment by mairaw** [comment]
Since we moved to a new site, this no longer repros. Closing this issue.
