### ISSUE TITLE
Can not add the apt-key with ubuntu 14.04

### ISSUE THREAD

**Issue by seb-bizeul** [dotnet/core-docs#40]
Here is the terminal output when I try to add the key from the server:

Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Hrb5ETPac2 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver keyserver.ubuntu.com --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
gpg: requesting key D3D831EF from hkp server keyserver.ubuntu.com
gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error

I tried several times but always give me an error. I precise that I'm using the ubuntu official image in a Docker container.
Regards

**Comment by Nitinr5** [comment]
Do we have a solution for this. I can see this problem on Ubuntu 14.04 VM.

nitin@nitin-VirtualBox:~$ sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
[sudo] password for nitin: 
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.Xa0Ys1wqA7 --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
**gpg: keyserver timed out
gpg: keyserver receive failed: keyserver error**

**I've tried port 80 as well but it clearly states that no such key is present.**

root@nitin-VirtualBox:/home/nitin# gpg --keyserver hkp://apt-mo.trafficmanager.net:80 --recv-keys 417A0893
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key 417A0893 from hkp server apt-mo.trafficmanager.net
**gpgkeys: key 417A0893 not found on keyserver**
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0

Please let me know if we have a solution for this.

Regards

**Comment by kwaazaar** [comment]
Is there a solution already? I run into this same problem.

**Comment by bsara** [comment]
I found a temporary solution for this here: https://github.com/dotnet/cli/issues/2189#issuecomment-220305609
