### ISSUE TITLE
Document how to setup test projects in .NET Core

### ISSUE THREAD

**Issue by danroth27** [dotnet/core-docs#401]
- Using dotnet test
- Using xUnit or your favorite test framework
- Integration with VS

**Comment by danroth27** [comment]
For ASP.NET Core we want to remove our DNX specific article (https://docs.asp.net/en/latest/testing/unit-testing.html) and instead point to the .NET Core docs.

**Comment by blackdwarf** [comment]
@danroth27 isn't this already in there now?

**Comment by BillWagner** [comment]
@danroth27 do you want the sample to move under the core docs repo as well?
