### ISSUE TITLE
libraries-with-cli.md is getting a little stale

### ISSUE THREAD

**Issue by mjrousos** [dotnet/core-docs#402]
Our [Libraries with CLI](https://github.com/dotnet/core-docs/blob/master/docs/libraries/libraries-with-cli.md) doc has some RC1-isms that we should update soon. For example, it mentions that the netstandardX.Y monikers aren't supported yet, so customers should use dotnetXY. Also, it says that the test command is only supported by dnx (not dotnet). Recent .NET CLI tools do support the test command, though.

The issues aren't very many, but they may be confusing for someone new to the technology. The doc could probably use a once-over to make sure that all of its dotnet-related statements/samples are still accurate.

**Comment by cartermp** [comment]
Yeah, I plan on updating this (#248).  I've been holding off on that until things got a little more stable.  It's probably a good time to update it here in the next week or so.

**Comment by mjrousos** [comment]
:+1: Seems like a good plan.

**Comment by mairaw** [comment]
Is this still relevant @cartermp? I'm guessing that with all the articles moving, this is the topic that is being discussed here: https://github.com/dotnet/core-docs/blob/master/docs/core/tutorials/libraries.md
