### ISSUE TITLE
.NET Core Concepts: Framing .NET Core

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#408]
We can benefit by having an article which focuses on framing .NET Core.  In short, this doc should be able to answer the following questions:

- "What is .NET Core and why should I care?"
- "How is it different from the other .NET implementations and why should I care?"
- "In what cases does .NET Core make sense for me?"

Answers to these questions have crept into the porting-to-core articles, and it's easy for them to creep into future docs.  It's better to have that sort of framing in a central location we can link to.

I propose the following structure as a starting point:

1.  What is .NET Core and why should I care?

   a. Overview of what .NET Core is, how it's composed of packages, and how that is rationalized with netstandard and netcoreapp
   b. Overview of the unique benefits of .NET Core as compared to .NET Framework and Mono

2. .NET Core compared with .NET Framework and Mono

   a. Overview of the key differences between .NET Core and (.NET Framework and Mono)
   b. Overview of the project system differences, why it matters, and links to project model docs

3.  When does .NET Core matter for me? 

   a. Overview of the types of things you can build on .NET Core
   b. Overview of the unique things you can do with .NET Core that you cannot do on .NET Framework and Mono

Thoughts?

/cc @richlander @davidfowl

**Comment by BillWagner** [comment]
I like this organization a lot. I also think it's important to address all these questions with two audiences in mind: developers that have been using netstandard for some time, and developers who are looking at netcore with fresh eyes, because of the platform independence. These two groups will often have very different answers for each of these questions.

**Comment by rpetrusha** [comment]
This is similar to the .NET Platform topic that I've started working on. Should I just incorporate some of the points that I wasn't going to cover into it, or should this replace it?

**Comment by BillWagner** [comment]
Does PR #429 address this?  /cc @cartermp

**Comment by rpetrusha** [comment]
Yes, it's intended to.

**Comment by stevehoag** [comment]
Closing; addressed by 429
