### ISSUE TITLE
Add article for Pinning your dependencies to RC2

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#414]
This article will be some point-in-time guidance for authoring libraries with RC2 bits.  The content should lay out the best ways to make sure you have packages which are guaranteed to work, along with showing a list of all packages that are a part of the RC2 release.  Ideally this list should be filterable, but that's something which will have to be handled outside of the docs.

/cc @richlander

**Comment by stevehoag** [comment]
@cartermp Hasn't this already been addressed?

**Comment by cartermp** [comment]
Yep, closing.
