### ISSUE TITLE
The style for tables makes them hard to read

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#418]
In [Writing Libraries with Cross Platform Tools#How to target .NET Core](http://dotnet.github.io/docs/core-concepts/libraries/libraries-with-cli.html#how-to-target-net-core), there is a table of mapping between `dotnet` and `netstandard` versions. On my computer (FF 45, Windows 10), it looks like this:

![dotnet → netstandard table screenshot](http://i.imgur.com/RMJAkaC.png)

The table is hard to read, because there is no space between the two columns.

It might also look better if the cells of the table had borders, but that's a matter of debate.

At the very least, the space between columns should be fixed by modifying the CSS for tables.

**Comment by svick** [comment]
Presumably fixed by #663.

**Comment by mairaw** [comment]
I was waiting until we go live to review your issues about UI.

**Comment by svick** [comment]
Yeah, tables look much better on docs.MS.
