### ISSUE TITLE
Create reference-source-like site for .Net Core

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#420]
[Reference Source](http://referencesource.microsoft.com/) and [Roslyn](http://source.roslyn.codeplex.com/) both have Roslyn-based sites that allow easy navigation of their source code. It would be nice if there was a similar site for .Net Core.

For me, the most important difference between the Roslyn-based site and using Github directly is finding some member. GitHub search is text-based, so it does not differentiate between declaration and usage. You can mostly get around that by searching for some string that's unique to the declaration (e.g. `"void Method"` for `void`-returning method `Method`), but that's cumbersome.

**Comment by cartermp** [comment]
This is something we've talked about and ultimately may want to do.  It would involve building a Roslyn index over corefx with [SourceBrowser](https://github.com/KirillOsenkov/SourceBrowser).

**Comment by svick** [comment]
I think this can now be closed, the site is at https://source.dot.net/.
