### ISSUE TITLE
Very wide tables and TOC overlap in API reference

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#422]
If some table in API reference gets too wide (due to a "word" that's too long), it starts overlapping with TOC, making both unreadable. For example, this happens in [one overload of the `FileStream` constructor](http://dotnet.github.io/api/System.IO.FileStream.html#System_IO_FileStream__ctor_System_String_System_IO_FileMode_System_IO_FileAccess_System_IO_FileShare_System_Int32_System_Boolean_):

![](http://imgur.com/D9GOyE2.png)

This specific example of this issue is likely going to be solved when XML docs are properly imported into corefx and docs start using them or by dotnet/corefx#8358 (which will make the references valid, so they will format properly), so solving the general issue might not be very important.

**Comment by mairaw** [comment]
Do you still see this issue with the overlapping TOC @svick? I can't repro on my machine.

Yep, for the references, as you noticed, they're not resolving because those APIs don't exist in Core. API reference still needs lots of work.

**Comment by svick** [comment]
This example is better, but still not fixed on my machine:

![](http://i.imgur.com/tQ2YoEB.png)

**Comment by mairaw** [comment]
What browser do you use? Just to see if that could be the difference. I've tried in 3 different ones and I cannot see this happening. :disappointed:

**Comment by svick** [comment]
Latest Firefox (46) on Windows 10. And I don't see this on IE or Edge, but that seems to be due to a different line-breaking algorithm. When I modify the cell to contain the following, I see it overlapping in Edge too:

> System.IO.FileStream.BeginReadSystem.Byte,System.Int32,System.Int32,System.AsyncCallback,System.Object) 

(I removed the `[]` after `System.Byte` and `(` after `BeginRead`.)

**Comment by mairaw** [comment]
Closing this since the layout is totally different in the new site.
