### ISSUE TITLE
Documentation issues and suggestions for dnx-migration

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/core-docs#426]
Several issues and suggestions found while migrating an RC1 app to RC2 in https://github.com/aspnet/Release/issues/102

- [x] https://github.com/dotnet/core-docs/blame/master/docs/core-concepts/dnx-migration.md#L101, needs to be changed to `buildOptions`
- [x] Some apps will need `preserveCompilationContext: true` to be set under `buildOptions`
- [x] Add link to new `project.json` schema. RC1 projects have nodes like `exclude` and `publishExclude` and include other files by default. This behaviour is different in RC2 where you need to explicitly specify which files to include in `copyToOutput` and `publish:include` nodes
- [x] Need to either remove or update `dnx451` to `net451`, this TFM shows up in many apps and templates. Also is `"Microsoft.NETCore.Platforms": "1.0.1-*"` still required?
- [x] Would be nice to link to a page giving more info for the TFMs. https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md
- [x] Add the fact that people need to change global.json version to RC2

**Comment by blackdwarf** [comment]
@JunTaoLuo some of the details in the above issue are actually asp.net specific so they should be part of the upgrading guide from ASP.NET Core RC1 -> RC2.

**Comment by JunTaoLuo** [comment]
@blackdwarf I suppose `preserve compilation context` makes sense to be in ASP.NET and that's been/being updated so that should be okay. I think global.json version change to RC2 is needed for all previous projects, even console apps. So I think it's best to have it in both migration documents.

**Comment by blackdwarf** [comment]
@JunTaoLuo all right, this is now in PR.

**Comment by JunTaoLuo** [comment]
@blackdwarf the PR is merged, any reason this issue is still open?

**Comment by blackdwarf** [comment]
@JunTaoLuo have no idea. But the issue has been fixed. Will close it.

**Comment by mairaw** [comment]
It seems that the PR was closed instead of merged @blackdwarf.

**Comment by blackdwarf** [comment]
@richlander said he merged it?

**Comment by mairaw** [comment]
Yes, but the actual merge action is not shown as usual @blackdwarf
