### ISSUE TITLE
Question about starting work on existing stubs

### ISSUE THREAD

**Issue by matthewreily** [dotnet/core-docs#43]
I would like to contribute to this project and was wondering if I need to open an issue to start working on an existing topic\stub.  For example, I would like to start working on https://github.com/dotnet/core-docs/blob/master/docs/development/using-visual-studio-code.rst. 

Do I open a new issue or just start working and submit a new pull request?

Thanks!

**Comment by BethMassi** [comment]
@matthewreily AWEOME you want to help here! Sorry I missed this, my watch settings are now set properly :smile: @blackdwarf how should we set up the workflow with community contributions? I think it's best to open an issue like this, tell us what you want to work on, and we can flush out your ideas in the thread.

**Comment by blackdwarf** [comment]
@matthewreily thanks for the interest! :) There are [contribution guidelines](https://github.com/dotnet/core-docs/blob/master/CONTRIBUTING.md) in the repo, but the gist of it is the following:

* Open an issue that describes what you want to write and then, as @BethMassi said, we iron out the details
* Fork the repo and create a new branch
* Write the article
* When done, create a PR, cc-ing @BethMassi @richlander and myself

We review and then merge! :)

**Comment by matthewreily** [comment]
Thank you both!
