### ISSUE TITLE
Code listings show distracting grey lines

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#436]
Code listings (created using <code>```</code>) show with distracting grey lines around the code. For example (from [Properties#Property Syntax](http://dotnet.github.io/docs/languages/csharp/properties.html#property-syntax)):

![](http://i.imgur.com/grvZGQR.png)

I think this is because the code is rendered as `<code>` inside `<pre>`:

```html
<pre><code class="lang-cs">public class Person
{
    public string FirstName;
    // remaining implementation removed from listing
}
</code></pre>
```

And [`code` has its own border](https://github.com/dotnet/core-docs/blob/77111f0d646319c121a1a9e2eb08c9a203714f53/template/styles/style.css#L142).

I don't know much about CSS, but I believe a solution would be to add the following to style.css:

```css
pre code {
    border: 0;
}
```

**Comment by mairaw** [comment]
@blackdwarf has this anything to do with the CSS style changes you applied yesterday?

**Comment by svick** [comment]
The new site does not have this issue.

**Comment by mairaw** [comment]
Thanks for reviewing those @svick!
