### ISSUE TITLE
API reference should indicate that a method is an extension method

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#440]
Currently, an extension method is listed as if it was a normal method. For example, the declaration for [`Enumerable.Any`](http://dotnet.github.io/api/System.Linq.Enumerable.html#System_Linq_Enumerable_Any__1_System_Collections_Generic_IEnumerable___0__) looks like this:

```c#
public static bool Any<TSource>(Collections.Generic.IEnumerable<TSource> source)
```

But it should indicate that the method is an extension method by specifying `this` on the first parameter, [just like MSDN does](https://msdn.microsoft.com/en-us/library/bb337697%28v=vs.100%29.aspx):

```c#
public static bool Any<TSource>(this Collections.Generic.IEnumerable<TSource> source)
```

**Comment by qinezh** [comment]
Hi @svick , it's fixed now
