### ISSUE TITLE
API Reference: Exception information often does not list the type of exception thrown

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/core-docs#441]
In many cases, the exception type is missing from the exception information. For example, in the  [String class ](http://dotnet.github.io/api/System.String.html), String.ctor(Char[], Int32, Int32) can throw two exceptions. The ArgumentNullException is listed for the first exception condition, but no exception type (it should be ArgumentOutOfRangeException) is listed for the second exception condition.

This appears to be a common problem throughout the doc set.

**Comment by mairaw** [comment]
@chenkennt can you take a look at this issue?

**Comment by superyyrrzz** [comment]
@mairaw It's fixed in DocFX 1.9.4. Now the content is correct.
