### ISSUE TITLE
Each page has a large dead space on top 

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#447]
Not sure if this was introduced by the CSS changes, but it would be good if the titles were closer to the top of the page:
![image](https://cloud.githubusercontent.com/assets/12971179/15340633/4396f970-1c3f-11e6-98ad-7893fcdcc826.png)

/cc @blackdwarf

**Comment by svick** [comment]
I believe [this line](https://github.com/dotnet/core-docs/blame/master/template/styles/main.css#L65-L67) (which indeed comes from #432) is responsible.

**Comment by blackdwarf** [comment]
*groan* Yeah, I needed to put that in because of the fixed navbar thing. Will fix it.

**Comment by BillWagner** [comment]
Styles have changed significantly, and this looks much better on http://docs.microsoft.com

Can this be closed?

/cc @mairaw @blackdwarf

**Comment by blackdwarf** [comment]
Closing. This was for the previous site and was transient since it had to do with temp CSS changes.
