### ISSUE TITLE
We need a manual for libraries that target .NET Core

### ISSUE THREAD

**Issue by richlander** [dotnet/core-docs#46]
This is for library creators and includes creating NuGet packages. It includes new packages and existing ones that also want to target .NET Core. It's basically the document that explains how to target the combination of .NET Core and NuGet v3 (3.3+). We need to explain how this relates to NuGet v2.

We should start with building class libraries and then explain how to package them. That's basically the two major sections of the doc.

We bias the document towards people who are already using PCL, since it targets the same problem space. This will allow us to get something out the door more quickly.

We should make this scenario-based:

- I support a small set of platforms, such as .NET Framework 4.5.1+ and .NET Core. What do I do?
- I support every .NET platform ever shipped. What do I do?

To start of, this is for folks using the myget feed. It lands as "stable" in RC1.

Library questions:

- Can I use PCL to target .NET Core?
- What's the difference between PCL and dotnet targeting?
- How can I target .NET Core and other platforms including PCL?
- How do I target specific platforms (I want it to run on Windows Phone, Xamarin iOS and Linux for ASP.NET).
- Which generation do I use?
- Which project type do I use?

Package questions:

- Can I use PCL to target .NET Core? Add "+dotnet"?
- What do I put as dependencies of my package?

**Comment by blackdwarf** [comment]
@richlander is this still on for //BUILD?

**Comment by ghogen** [comment]
Per discussion in meeting, we're closing this issue.
