### ISSUE TITLE
Create content for ".NET Core packages and metapackages" topic

### ISSUE THREAD

**Issue by BillWagner** [dotnet/core-docs#467]
This issue tracks the content for this topic http://dotnet.github.io/docs/core-concepts/packages-metapackages.html

/cc @mairaw @blackdwarf for details on what this topic should cover

**Comment by mairaw** [comment]
@blackdwarf do you know what we want to cover here? do we want to explain what those are and list the ones available like NETStandard.Library or Microsoft.NETCore.App?

**Comment by blackdwarf** [comment]
@richlander would know though I assume your assumption is correct @mairaw

**Comment by stevehoag** [comment]
@richlander Referenced topic no longer exists - should we close this?

**Comment by mairaw** [comment]
I think we can close this. We have this topic on docs now:
[Packages, Metapackages and Frameworks](https://docs.microsoft.com/en-us/dotnet/articles/core/packages)
