### ISSUE TITLE
Create the topic for Core Concepts: ".NET Core Application Deployment Concepts"

### ISSUE THREAD

**Issue by BillWagner** [dotnet/core-docs#471]
This issue tracks the creation of this topic: http://dotnet.github.io/docs/core-concepts/app-deployment.html

It may be that this issue (and the referenced page) can be closed. Everything for this topic may be covered in the section on "Packaging and Deploying Applications". See this page: http://dotnet.github.io/docs/scenarios/deployment/index.html And issues #294 #295 #296 #297 #298 and #299.

/cc @mairaw @blackdwarf

**Comment by stevehoag** [comment]
Closing; addressed by 471
