### ISSUE TITLE
Building API reference locally

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#478]
Since it seems [PRs for API reference extensions](https://github.com/dotnet/core-docs/pulls?q=is%3Apr+%22Update+and+rename+new+to%22) are starting to come in, it would be nice if there was some way to build the API reference (including those extensions) on my machine.

Just running `docfx build` doesn't seem to do it and I didn't find anything in [the contributing docs](https://github.com/dotnet/core-docs/blob/e5e81ed/CONTRIBUTING.md#building-the-docs) either.

**Comment by svick** [comment]
This seems to work now. I believe it was fixed by #496.

**Comment by mairaw** [comment]
Good to know @svick. I just tested this last night so I wasn't sure what was the issue you were running into.
