### ISSUE TITLE
Is a unit test project a console app or a class lib?

### ISSUE THREAD

**Issue by danroth27** [dotnet/core-docs#499]
I was following the http://dotnet.github.io/docs/core-concepts/testing/unit-testing-with-dotnet-test.html doc and I got a bit confused in the "Creating the test project" section. I couldn't tell if I was supposed to create a console app project or a class lib project (or maybe some sort of hybrid?).

The text says:

>Next, cd into the 'test' directory, and create the PrimeServices.Tests directory. CD into the PrimeServices.Tests directory and create a new project using dotnet new. Once again, dotnet new creates a console application, and you'll need to modify project.json to create a class library project by removing the buildOptions node.

So, I must be creating a class lib, right? But then it says:

> Finally, you need to set the framework node to use netcoreapp1.0, and include the required imports to get xunit to work with RC2:

Isn't that the TFM for creating apps not class libs? I thought class libs generally target netstandard, but when I tried that it didn't work.

**Comment by danroth27** [comment]
@blackdwarf

**Comment by BillWagner** [comment]
@danroth27 @blackdwarf I'll make that more clear.

Short version: you are creating a console app, but you don't want the entry point in the test assembly because it's in the runner (which is a NuGet package).

**Comment by blackdwarf** [comment]
@BillWagner precisely. Also, because of the package graph.
