### ISSUE TITLE
API Reference: Some type names include part of namespace name

### ISSUE THREAD

**Issue by rpetrusha** [dotnet/core-docs#501]
In the System.Text namespace at http://dotnet.github.io/api/System.Text.html, two type names include a portion of the namespace name:

- "Text.Encoding" should be "Encoding"

-  "Text.StringBuilder" should be "StringBuilder"

/cc @blackdwarf

**Comment by rpetrusha** [comment]
Another instance occurs at http://dotnet.github.io/api/Windows.Foundation.html; "Foundation.Point" should be "Point"

**Comment by qinezh** [comment]
Hi @rpetrusha , it's fixed now
