### ISSUE TITLE
Why does Interpreting Expressions not use ExpressionVisitor?

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#511]
The article [Interpreting Expressions](https://dotnet.github.io/docs/languages/csharp/expression-trees-interpreting.html) is about creating a custom visitor for expression trees from scratch and at the end links to GitHub search, which is meant to find open source expression visitors.

But [.Net Core already contains `ExpressionVisitor`](https://dotnet.github.io/api/System.Linq.Expressions.ExpressionVisitor.html) (and [.Net Framework contained it since .Net 4.0](https://msdn.microsoft.com/en-us/library/system.linq.expressions.expressionvisitor(v=vs.110).aspx)). Why is it not used or even mentioned here? I think it would simplify the code and also promote good practices.

I didn't find this mentioned in #205, but I didn't read the whole discussion, so I could have missed it.

CC: @BillWagner

**Comment by BillWagner** [comment]
@svick You're right. `ExpressionVisitor` should be mentioned and highlighted.

I'd like to keep the content that creates the custom visitor. It does help readers learn about Expression Trees in general, and how to treat code as a data structure. Do you want to create a pull request for this?
