### ISSUE TITLE
Articles not in the TOC

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#514]
There seems to be quite a lot of articles that are not part of [the site TOC](https://github.com/dotnet/core-docs/blob/master/docs/toc.md). Specifically (excluding 🔧 article stubs and TOC articles):

* [async/async-csharp-vb.md](https://dotnet.github.io/docs/async/async-csharp-vb.html): This seems to be a copy of [languages/csharp/async.md](https://dotnet.github.io/docs/languages/csharp/async.html), and a remnant of #175. Probably can be deleted.
* [async/async-fsharp.md](https://dotnet.github.io/docs/async/async-fsharp.html): Maybe put it under Learning F#? Or delete it, unless more coverage on F# is planned.
* [async/async-overview.md](https://dotnet.github.io/docs/async/async-overview.html): Short article, almost a TOC, maybe include into C#/F# async articles?
* [concepts/assembly-format.md](https://dotnet.github.io/docs/concepts/assembly-format.html), [concepts/class-libraries.md](https://dotnet.github.io/docs/concepts/class-libraries.html), [concepts/common-type-system.md](https://dotnet.github.io/docs/concepts/common-type-system.html), [concepts/delegates-lambdas.md](https://dotnet.github.io/docs/concepts/delegates-lambdas.html), [concepts/framework-libraries.md](https://dotnet.github.io/docs/concepts/framework-libraries.html), [concepts/gc-overview.md](https://dotnet.github.io/docs/concepts/gc-overview.html), [concepts/generics.md](https://dotnet.github.io/docs/concepts/generics.html), [concepts/linq.md](https://dotnet.github.io/docs/concepts/linq.html), [concepts/managed-code.md](https://dotnet.github.io/docs/concepts/managed-code.html), [concepts/native-interop.md](https://dotnet.github.io/docs/concepts/native-interop.html): Since [concepts/index.md](https://dotnet.github.io/docs/concepts/index.html) is the top level Learn .NET section, these articles probably belong directly under it.
* [core-concepts/core-sdk/sdk-overview.md](https://dotnet.github.io/docs/core-concepts/core-sdk/sdk-overview.html), [core-concepts/core-sdk/cli/dotnet-test-protocol.md](https://dotnet.github.io/docs/core-concepts/core-sdk/cli/dotnet-test-protocol.html): Their parents have a TOC entry, so these belong under them.
* [essentials/numericsincore.md](https://dotnet.github.io/docs/essentials/numericsincore.html): Already handled by #507.
* [essentials/exceptions/exception-class-properties.md](https://dotnet.github.io/docs/essentials/exceptions/exception-class-properties.html), [essentials/exceptions/exception-hiearchy.md](https://dotnet.github.io/docs/essentials/exceptions/exception-hiearchy.html), [essentials/exceptions/exceptions-best-practices.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-best-practices.html), [essentials/exceptions/exceptions-catch-specific-exceptions.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-catch-specific-exceptions.html), [essentials/exceptions/exceptions-create-user-defined.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-create-user-defined.html), [essentials/exceptions/exceptions-throw-exceptions.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-throw-exceptions.html), [essentials/exceptions/exceptions-use-finally-blocks.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-use-finally-blocks.html), [essentials/exceptions/exceptions-use-try-catch-block.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-use-try-catch-block.html), [essentials/exceptions/exceptions-user-filtered-handlers.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-user-filtered-handlers.html), [essentials/exceptions/exceptions.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions.html): These belong under [essentials/exceptions.md](https://dotnet.github.io/docs/essentials/exceptions.html) which is already in the TOC.
* [essentials/exceptions/exceptions-com-interop.md](https://dotnet.github.io/docs/essentials/exceptions/exceptions-com-interop.html): Should be deleted per https://github.com/dotnet/core-docs/pull/344#discussion_r57095278.
* [languages/csharp/delegate-class.md](https://dotnet.github.io/docs/languages/csharp/delegate-class.html), [languages/csharp/delegates-overview.md](https://dotnet.github.io/docs/languages/csharp/delegates-overview.html), [languages/csharp/delegates-patterns.md](https://dotnet.github.io/docs/languages/csharp/delegates-patterns.html), [languages/csharp/delegates-strongly-typed.md](https://dotnet.github.io/docs/languages/csharp/delegates-strongly-typed.html), [languages/csharp/distinguish-delegates-events.md](https://dotnet.github.io/docs/languages/csharp/distinguish-delegates-events.html), [languages/csharp/event-pattern.md](https://dotnet.github.io/docs/languages/csharp/event-pattern.html), [languages/csharp/events-overview.md](https://dotnet.github.io/docs/languages/csharp/events-overview.html), [languages/csharp/modern-events.md](https://dotnet.github.io/docs/languages/csharp/modern-events.html): Put under [languages/csharp/delegates-events.md](https://dotnet.github.io/docs/languages/csharp/delegates-events.html) and remove Previous and Next links from articles.
* [languages/csharp/expression-classes.md](https://dotnet.github.io/docs/languages/csharp/expression-classes.html), [languages/csharp/expression-trees-building.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-building.html), [languages/csharp/expression-trees-execution.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-execution.html), [languages/csharp/expression-trees-explained.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-explained.html), [languages/csharp/expression-trees-interpreting.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-interpreting.html), [languages/csharp/expression-trees-summary.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-summary.html), [languages/csharp/expression-trees-translating.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-translating.html): Put under [languages/csharp/expression-trees.md](https://dotnet.github.io/docs/languages/csharp/expression-trees.html) and remove Previous and Next links.
* [languages/csharp/implicitly-typed-lambda-expressions.md](https://dotnet.github.io/docs/languages/csharp/implicitly-typed-lambda-expressions.html): This is a footnote for [languages/csharp/expression-trees-interpreting.md](https://dotnet.github.io/docs/languages/csharp/expression-trees-interpreting.html#examining-a-simple-addition-expression), and should stay outside the TOC.
* [project-model/project-json-reference.md](https://dotnet.github.io/docs/project-model/project-json-reference.html): Probably put directly under .Net Core concepts for now, since the other project-model articles are 🔧stubs and not in the TOC.
* [tutorials/getting-started-with-csharp/console-teleprompter.md](https://dotnet.github.io/docs/tutorials/getting-started-with-csharp/console-teleprompter.html), [tutorials/getting-started-with-csharp/console-webapiclient.md](https://dotnet.github.io/docs/tutorials/getting-started-with-csharp/console-webapiclient.html), [tutorials/getting-started-with-csharp/microservices.md](https://dotnet.github.io/docs/tutorials/getting-started-with-csharp/microservices.html), [tutorials/getting-started-with-csharp/working-with-linq.md](https://dotnet.github.io/docs/tutorials/getting-started-with-csharp/working-with-linq.html): Put under [tutorials/index.md](https://dotnet.github.io/docs/tutorials/index.html).

Do you agree with my assessment of what to do with these?

**Comment by mairaw** [comment]
I've noticed this too and wanted to get this fixed. I'll take a look more closely. There's also the SDK overview which is not in the TOC. Thanks for your analysis @svick.

**Comment by BillWagner** [comment]
@svick Thank you for the work, and the analysis.

One question I have is how many levels do we want in the TOC? 

In the case of the expression tree articles, they are meant to be read in order. That's why they have the previous and next links. (They were broken down into multiple pages due to their length.) 

@svick Do you think that these stand on their own, or would a reader be lost by dropping into the middle of the set? If the latter, how would we indicate that these are related articles, and they are meant to be read in sequence?

Thoughts?

**Comment by mairaw** [comment]
I think that the recommended is to have 3 levels @BillWagner. The C# area only has 2, so adding the missing entries shouldn't be an issue right?

**Comment by svick** [comment]
@BillWagner I think they mostly stand on their own. But I think keeping the Previous and Next links would be fine too.

**Comment by BillWagner** [comment]
@mairaw Thanks for clarifying. I just wanted to be consistent.

@svick I would prefer keeping the _previous_ and _next_ links as well as adding these articles into the TOC. Do you want to make those changes?

**Comment by svick** [comment]
@BillWagner Yeah, I will make the changes.

**Comment by cartermp** [comment]
> async/async-csharp-vb.md: This seems to be a copy of languages/csharp/async.md, and a remnant of #175. Probably can be deleted.
async/async-fsharp.md: Maybe put it under Learning F#? Or delete it, unless more coverage on F# is planned.

These will eventually have a place.  #214 will be where that happens.  I'll probably get around to updating those post-.NET Core RTM.
