### ISSUE TITLE
Inconsistent heading styles

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#522]
The styles of the various heading levels aren't consistent with what level they represent. I noticed this on the [Async in F#](https://dotnet.github.io/docs/async/async-fsharp.html#a-note-on-threads) article, where the level 3 heading *A Note on Threads* looks much larger and bolder than the level 2 heading *How to Add Parallelism to Async Code*:

![](http://i.imgur.com/nuEVPT6.png)

The overall structure looks like this:

![](http://i.imgur.com/mMUjRvF.png)

So, Level 3 looks significantly larger than Level2 and Level 2 and Level 4 have the same size.

This should be fixed, so that higher level headings clearly look more important.

**Comment by BillWagner** [comment]
@bradygaster is this tracked internally?

**Comment by mairaw** [comment]
I ran into the same issue last week while writing a new topic and @blackdwarf pointed out it was a CSS problem with the site.

**Comment by svick** [comment]
The heading structure on the new site looks fine:

![](http://i.imgur.com/aJEAkoV.png)
