### ISSUE TITLE
Getting a 404 for some of our documentation

### ISSUE THREAD

**Issue by piotrpMSFT** [dotnet/core-docs#525]
## Steps to reproduce
https://dotnet.github.io/docs/getting-started/getting-started/cli-console-app-tutorial.md

## Expected  behavior
I should see the tutorial

## Actual behavior
I get a 404 page

## Environment data
`dotnet --info` output:

moved from https://github.com/dotnet/cli/issues/3534 on behalf of @chrisboh

**Comment by mairaw** [comment]
How are you getting to this URL? The right one would be https://dotnet.github.io/docs/getting-started/cli-console-app-tutorial.html

**Comment by piotrpMSFT** [comment]
@Chrisboh

**Comment by svick** [comment]
I see this link in [Getting Started](https://dotnet.github.io/docs/getting-started/index.html) (the article, not the left-hand TOC). I plan to go through these TOC articles when fixing #514, so I'll fix this there too if nobody does it before then.

**Comment by mairaw** [comment]
Thanks @svick. I'll fix that one since we're still discussing the TOC changes. @Chrisboh, please confirm that's where you saw that 404. Thanks!

**Comment by Chrisboh** [comment]
@svick Yes that is the link I clicked that caused this.
