### ISSUE TITLE
Article headings do not wrap correctly

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#538]
When article heading is longer than the space reserved for it, the heading is often wrapped inside a word. This happens for example with [Building simple C# solutions with Visual Studio](https://dotnet.github.io/docs/scenarios/solution-authoring/vs-golden-path.html):

![](http://i.imgur.com/aLCrfaA.png)

Notice how the word "Visual" is split into "Visua" and "l".

I think article headings should be wrapped between words, as usual.

**Comment by mairaw** [comment]
With the new site I don't think that is true any longer so I'm closing this one. e.g.
https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli

Please let me know if that's not the case.
