### ISSUE TITLE
404 for main collections topic

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#543]
After we removed the index.md file from the collections folder, this link is broken and gives a 404:
https://dotnet.github.io/docs/essentials/collections/collections-and-data-structures.html

Local build works fine and other directories with similar structure work fine too, such as:
https://dotnet.github.io/docs/essentials/exceptions/exceptions.html

Do I need an index.md file for a TOC node?

/cc @blackdwarf

**Comment by svick** [comment]
The old URL (from before 28290f6) works for me: https://dotnet.github.io/docs/essentials/collections/Collections-and-Data-Structures.html.

Could that be the cause of the problem?

**Comment by chenkennt** [comment]
This is file name casing issue, the actual page is:
https://dotnet.github.io/docs/essentials/collections/Collections-and-Data-Structures.html
But actually the file name in GitHub is lower case.
@qinezh please help fix.

**Comment by mairaw** [comment]
we renamed all the files to lowercase so not sure if it's something stale on the build server or what.

Also, please advise if it's good practice to have the index.md file for TOC nodes. It seems that if we want to access the directory without any file name, having the index.md would accomplish that.

**Comment by qinezh** [comment]
It's fixed after set `git config core.ignorecase false`. By default, git would consider that `fileName.txt` is same as `FileName.txt`.

**Comment by mairaw** [comment]
Thanks @qinezh!
