### ISSUE TITLE
Inherited explicitly imeplemented members are not linked correctly in Inherited Members

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#548]
The list of Inherited Members for [`ReadOnlyObservableCollection<T>`](https://dotnet.github.io/api/System.Collections.ObjectModel.ReadOnlyObservableCollection%601.html) contains several members that are explicitly implemented and inherited from `ReadOnlyCollection<T>`. But those members are not linked in the list and are shown with their full name, e.g.: `System.Collections.ObjectModel.ReadOnlyCollection<T>.System.Collections.Generic.ICollection<T>.Clear()`.

**Comment by mairaw** [comment]
@chenkennt, is this new functionality? I don't remember seeing this section before. We should talk about this implementation. @bradygaster

**Comment by rpetrusha** [comment]
It has numerous problems, including mislabeling some members (in [FileStream](https://dotnet.github.io/api/System.IO.FileStream.html), there's link to an inherited Stream.Null field that's incorrectly named FileStream; and .NET Framework and .NET Core inherited members are shown. But it would be better to list inherited members in the member's list, and not in a separate list of inherited members.

**Comment by chenkennt** [comment]
@vwxyzh please help take a look

**Comment by svick** [comment]
The new site does not seem to have an inherited members list, so this issue does not apply anymore. For example: [`ReadOnlyObservableCollection<T>`](https://docs.microsoft.com/en-us/dotnet/core/api/system.collections.objectmodel.readonlyobservablecollection-1)
