### ISSUE TITLE
C# tutorials - properties

### ISSUE THREAD

**Issue by stevehoag** [dotnet/core-docs#55]
Should teach the basics of declaring and using properties in C#.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by BillWagner** [comment]
I'll work on this, if someone wants to assign it to me.

**Comment by stevehoag** [comment]
Assigned to Bill.
