### ISSUE TITLE
Use docfx syntax for notes

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#553]
[docfx has special syntax for notes](https://dotnet.github.io/docfx/spec/docfx_flavored_markdown.html#note-warning-tip-important-):

```md
> [!NOTE] Text of note
```

This syntax is used in some articles, e.g. [*How to use the Try/Catch block to catch exceptions*](https://dotnet.github.io/docs/essentials/exceptions/exceptions-use-try-catch-block.html):

![](http://i.imgur.com/arHEcgS.png)

But some articles use this syntax instead:

```md
> **Note**
>
> Text of note
```

For example, [*.NET Primer*](https://dotnet.github.io/docs/concepts/primer.html#programming-languages):

![](http://i.imgur.com/wRp7WkM.png)

Should the special docfx syntax be used consistently across the whole documentation for notes?

Also, with the current style, it's not clear where docfx-style notes end. Should that be changed?

**Comment by SamuelEnglard** [comment]
Personally I much prefer the second style, and I'm using it myself. I've made a slight modification based on MSDN library though:

```
> 📝 **NOTE**
> Text of note
```

**Comment by svick** [comment]
@SamuelEnglard I think that documentation should have consistent style, not every author using their own style.

And with the special syntax, it should be easy to modify the look using CSS.

**Comment by SamuelEnglard** [comment]
@svick I was not suggesting we each use our own style, if I sounded that way my bad.

And I'm not seeing how the special syntax allows that?

**Comment by svick** [comment]
@SamuelEnglard 

```md
> [!NOTE] Text of note
```

generates:

```html
<div class="NOTE"><h5>NOTE</h5><p>Text of note</p>
</div>
```

which means it can be styled using CSS.

On the other hand

```md
> **Note**
>
> Text of note
```

is just a normal quote, so it generates:

```html
<blockquote><p><strong>Note</strong></p>
<p>Text of quote</p>
</blockquote>
```

so it can't be easily styled to look different than a quote.

**Comment by SamuelEnglard** [comment]
Ah, that is a good point

**Comment by mairaw** [comment]
Hi @svick, I agree with you. We'll be working on achieving consistency across the docs in this aspect and in other aspects in the next few weeks and also having that information available to everyone contributing to our docs. We're going to be using the docfx one across the board. The style will also change to make the note delimitation more noticeable.
> [!NOTE]
> This is NOTE
