### ISSUE TITLE
Need to remove RC2 references and update version numbers for the RTM release

### ISSUE THREAD

**Issue by mairaw** [dotnet/core-docs#576]
We have several topics that are still targeting RC2 and contain the package numbers for RC2. They need to be reviewed for RTM.

For example:
https://dotnet.github.io/docs/scenarios/library-authoring/trimming.html
https://dotnet.github.io/docs/scenarios/library-authoring/fastening-libraries-to-rc2.html

**Comment by cartermp** [comment]
Yup, I'll handle this and update version numbers to be fixed for RTM as well.

**Comment by BillWagner** [comment]
@cartermp I'd started putting together a bash / sed script to find (and later update) occurrences of the rc2 build in md and project.json files. I'll be working on it a bit more tomorrow, if that would help.

**Comment by BillWagner** [comment]
My last search of our samples, along with @dend 's CI indicates we've found all these.

Time to close this?

**Comment by dend** [comment]
CI doesn't detect any rc2 dependencies, so we should be good.

**Comment by BillWagner** [comment]
Sounds good.  Closing.
