### ISSUE TITLE
Articles not in the TOC, round 2

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#625]
After recent changes to the TOC and before Monday's launch, it seems it's time to revisit #514 again.

So, articles that I believe should be in the TOC but aren't:

* [core/app-types.md](https://github.com/dotnet/core-docs/tree/master/docs/core/app-types.md),  [core/packages.md](https://github.com/dotnet/core-docs/tree/master/docs/core/packages.md),  [core/sdk.md](https://github.com/dotnet/core-docs/tree/master/docs/core/sdk.md) 
* [scenarios/solution-authoring/target-dotnetcore-with-msbuild.md](https://github.com/dotnet/core-docs/tree/master/docs/scenarios/solution-authoring/target-dotnetcore-with-msbuild.md) 
* [standard/porting/tooling.md](https://github.com/dotnet/core-docs/tree/master/docs/standard/porting/tooling.md)

I'm not sure where in the TOC do these articles belong now, or whether to include some of them at all, so I won't be creating a PR for this.

**Comment by BillWagner** [comment]
I checked today (after quite a bit of changing in the TOC and the repo.)

The three under core in your first bullet point are still bugs. 
The last two have moved and should now be fixed.

**Comment by svick** [comment]
Here is an updated list:

* [core/app-types.md](https://docs.microsoft.com/en-us/dotnet/articles/core/app-types), [core/packages.md](https://docs.microsoft.com/en-us/dotnet/articles/core/packages), [core/sdk.md](https://docs.microsoft.com/en-us/dotnet/articles/core/sdk)
* [core/porting/libraries.md](https://docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries)
* [tutorials/supporting-frameworks/analyzing-portability.md](https://docs.microsoft.com/en-us/dotnet/articles/tutorials/supporting-frameworks/analyzing-portability)
