### ISSUE TITLE
C# tutorials - delegates

### ISSUE THREAD

**Issue by stevehoag** [dotnet/core-docs#63]
Shows how to map delegates to static and instance methods, and how to combine them (multicast).

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by rtandel** [comment]
I'll move the conversation to this issue. I'm almost to this topic in my C# book so I can do this one really soon. 
I am interested in "We were talking about porting some "getting started" .NET Framework content to core. It both needs to be massaged into markdown and validated that it the content applies to Core. We're going to start that exercise soon, but could use some help." 
I will have delegates done as soon as possible though.

**Comment by BillWagner** [comment]
I'll take this one if someone wants to assign it to me. I'll also work on #64 at the same time, since they are related concepts.

**Comment by cartermp** [comment]
Done!

**Comment by BillWagner** [comment]
I'm going to break this one into the following tasks to avoid a huge PR (like with expression trees):
[ ] Create Placeholders with links for navigation
[ ] Write Overview Article
[ ] Delegate class and delegate keyword
[ ] Strongly Typed Delegates
[ ] Delegate Patterns and Practices

I'll suggest that I create separate issues for each of those tasks, and create PRs for each of them (linking them here).

**Comment by stevehoag** [comment]
Makes sense.

**Comment by BillWagner** [comment]
I created all the sub-issues. and updated the comment above. Can someone assign the new issues to me

**Comment by stevehoag** [comment]
Done

**Comment by BillWagner** [comment]
Everything for this section is in place. There are 5 PRs referenced above for the placeholders, and each article. It should be ready to review.

**Comment by BillWagner** [comment]
This should be closed, as all PRs have been merged.
