### ISSUE TITLE
C# tutorials - events

### ISSUE THREAD

**Issue by stevehoag** [dotnet/core-docs#64]
Shows how to declare, invoke, and hook up to events in C#. 

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by BillWagner** [comment]
I'll take this, if someone wants to assign it to me. I'll work on it along with #63 as they are related.

**Comment by cartermp** [comment]
Done!

**Comment by BillWagner** [comment]
I'm going to break this one into the following tasks to avoid a huge PR (like with expression trees):

[ ] Create Placeholders with links for navigation
[ ] Write Overview Article
[ ] Event Pattern
[ ] Modern Events:  without the (object sender, EventArgs args) prototype
[ ] Distinguishing events from delegates

I'll suggest creating separate sub-issues for each of these articles and creating a PR when each article is ready

**Comment by stevehoag** [comment]
Also makes sense...

**Comment by cartermp** [comment]
Sounds good.

Side note: Github *really* needs to get more advanced issue tracking for exactly this kind of scenario.

**Comment by BillWagner** [comment]
I created all the sub-issues. and updated the comment above. Can someone assign the new issues to me?

**Comment by cartermp** [comment]
Done!

**Comment by BillWagner** [comment]
This should now be closed, as all the sub-issues have been completed and merged.
