### ISSUE TITLE
Edit links on doc pages are broken

### ISSUE THREAD

**Issue by naamunds** [dotnet/core-docs#682]
The "EDIT" button on the right side of the documentation pages (e.g. https://docs.microsoft.com/en-us/dotnet/articles/core/index) redirects to a non-existent GitHub page (https://github.com/dotnet/core-docs/blob/stage/docs/core/index.md). It looks like the issue is that they go to the "stage" branch instead of the "master" branch, which no longer exists. Replacing "stage" with "master" in the URL works.

**Comment by mairaw** [comment]
Thanks for reporting this @naamunds. I'm looking into that!

**Comment by mairaw** [comment]
This should be fixed now. Closing the issue.
