### ISSUE TITLE
cloudflare blocked in china, i can't select linux/osx at homepage

### ISSUE THREAD

**Issue by WG-Com** [dotnet/core-docs#688]
page : https://www.microsoft.com/net/core

js can't load : https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js

**Comment by mairaw** [comment]
@BethMassi @davidcsa @shanselman can one of you take a look at this issue? Should it be filed somewhere else since this is for the marketing site and not the docs?

**Comment by neusamir** [comment]
This should be fixed now. We now use a local version of the javascript instead of relying on the cdn. In the future we may move to our own cdn (I hope).

**Comment by mairaw** [comment]
Thanks @neusamir. @WG-Com, can you please confirm you're not experiencing the issue anymore?

**Comment by WG-Com** [comment]
@mairaw   ok now
