### ISSUE TITLE
Language switcher doesn't work

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/core-docs#712]
No matter which language I select I always get my browser's language in the URL:
![Language](https://cloud.githubusercontent.com/assets/1376924/16474122/225b4458-3e74-11e6-86f5-82819f673e1c.gif)

**Comment by mairaw** [comment]
Yes, I'm seeing a similar behavior too. And also the language selector doesn't show up in Chrome.

We don't have localized content for .NET Core yet but we did launch for EMS today and it's the same behavior.

@chenkennt, are you guys aware of this issue?

**Comment by mairaw** [comment]
I'm following up with our engineering team. From what I can see, it now shows up in Chrome and it works in Chrome, but fails on IE/Edge. Haven't tested other browsers.

**Comment by akoeplinger** [comment]
I'm still seeing the same behavior as before in Chrome, switching the language has no effect (I don't expect localized content, but my choice should be reflected in the switcher and URL).

**Comment by akoeplinger** [comment]
Ah, the switcher works fine on pages that actually have localized content such as https://docs.microsoft.com/en-us/intune/understand-explore/introduction-to-microsoft-intune.

So the issue only seems to be in remembering your selection when the relevant content isn't available.

**Comment by mairaw** [comment]
Is it working now @akoeplinger? It's supposed to be fixed for all browsers now.

**Comment by akoeplinger** [comment]
@mairaw No, I still see the problem of it not switching when there's no localized content available, e.g. like on https://docs.microsoft.com/de-de/dotnet/articles/core/index

**Comment by SonjaSaltzman** [comment]
It works for me on Edge (clicking on unloc'd topic, switching locales changes the locale in the path)

**Comment by akoeplinger** [comment]
Yes, after clearing cookies and cache for docs.microsoft.com it now works in Chrome for me too. Thanks!

**Comment by mairaw** [comment]
Good to know @akoeplinger!
