### ISSUE TITLE
Update links to C# tutorials on docs/csharp/index.md  

### ISSUE THREAD

**Issue by jaredpsimpson** [dotnet/core-docs#715]
The C# tutorials were moved to the csharp folder, but not all of the links were updated. The getting-started-with-csharp folder needs to be removed from the link on csharp/index.md.

**Comment by cartermp** [comment]
Closing as the PR you PR was merged.  Thanks, @jaredpsimpson!

**Comment by mairaw** [comment]
Yep, super thanks! BTW, next time if you want you can close an issue using the keyword Fixes in your commit message, like Fixes #715. 
See here for more info: https://help.github.com/articles/closing-issues-via-commit-messages/
