### ISSUE TITLE
Wrong platform version (1.0.0-rc2.3002702) on examples at https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/core-docs#722]
The pets example has the wrong platform version (1.0.0-rc2.3002702).

The same for the project with the tests.

/cc @BillWagner

**Comment by BillWagner** [comment]
Fixed in PR #719 

Fixes will go live tomorrow AM.
