### ISSUE TITLE
Uncompilable code at https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-with-xplat-cli

### ISSUE THREAD

**Issue by paulomorgado** [dotnet/core-docs#723]
The Fibonacci sequence generator example doesn't compile because in the instructions you keep the using `static System.Console;` directive but changed from using plain `WriteLine` to `Console.WriteLine`.

The example should either be:

    using System;
    using NumberFun;

and

    public static void Main(string[] args)
    {
        var generator = new FibonacciGenerator();
        foreach (var digit in generator.Generate(15))
        {
            Console.WriteLine(digit);
        }
    }

or:

    using static System.Console;
    using NumberFun;

and

    public static void Main(string[] args)
    {
        var generator = new FibonacciGenerator();
        foreach (var digit in generator.Generate(15))
        {
            WriteLine(digit);
        }
    }

/cc @BillWagner

**Comment by mairaw** [comment]
Obrigada @paulomorgado. I believe PR #719 also solves this issue.

**Comment by BillWagner** [comment]
I think I caught this in PR #719, as @mairaw mentions. @paulomorgado can you verify and close if it is fixed?  Thanks for reporting this.

**Comment by paulomorgado** [comment]
Yes, it does, @BillWagner!
