### ISSUE TITLE
C# tutorials - expression trees

### ISSUE THREAD

**Issue by stevehoag** [dotnet/core-docs#73]
SHow how to use expression trees to enable dynamic modification of executable code in C#.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by BillWagner** [comment]
I'll work on this. Will someone please assign it to me?

**Comment by stevehoag** [comment]
Done - should be assigned to you now. Thanks!

**Comment by BillWagner** [comment]
This should be closed, as it was addressed in PR #205
