### ISSUE TITLE
C# tutorials - iterators

### ISSUE THREAD

**Issue by stevehoag** [dotnet/core-docs#74]
Show how to use iterators in c# to step through collections and return elements one at a time.

Tutorials should include one or more code examples, each example should also show expected output and should include an explanation of the code where it isn't obvious. Examples shouldn't be dependent on a specific IDE or target platform.

**Comment by BillWagner** [comment]
I'll take this. Can someone assign it to me?

**Comment by mairaw** [comment]
Done

**Comment by BillWagner** [comment]
This should be closed (fixed in PR #172) I didn't mark that in the PR.
