### ISSUE TITLE
Question: (How) Can I use the docs.html template for my docfx project?

### ISSUE THREAD

**Issue by EnCey** [dotnet/core-docs#740]
According to docfx.json the .NET core docs use the `docs.html` template for docfx (`"template": [ "docs.html" ]` ).

This doesn't seem to be available in vanilla docfx (but it is a lot prettier than the docfx default theme).

Is it available somewhere and are we allowed to use it for our internal docs projects?

**Comment by mairaw** [comment]
@chenkennt can you help with this question?

**Comment by mairaw** [comment]
@EnCey I'll ask you that you open this issue on the docfx repo instead: https://github.com/dotnet/docfx

You might get better traction than here.
