### ISSUE TITLE
Namespace summary in API reference should not show attributes

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#809]
The right column of namespace summaries can be fairly busy, especially on small displays. There is no need to make it worse by including all attributes specified for each class. An example, from [System.Collections.Generic](https://docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic):

![](http://i.imgur.com/7EEsiqW.png)

MSDN does not even show attributes like `[DebuggerDisplay]` on the type page, though it does show attributes like `[ComVisible]` or `[Serializable]` (example: [`Dictionary<TKey, TValue>`](https://msdn.microsoft.com/en-us/library/xfhwa508(v=vs.110).aspx)). I think the namespace summary page should not show any attributes at all.

**Comment by mairaw** [comment]
I agree with you @svick. I believe we had filed bugs for both of the issues you're reporting internally. I'll check the status on those.

**Comment by richlander** [comment]
I'd question whether type signatures are needed on namespace summary pages at all. The type name on its own seems adequate.

**Comment by rpetrusha** [comment]
I agree.

**Comment by mairaw** [comment]
I had requested the signatures to be removed from namespace pages on a feature request. I can check the status when I'm back.

**Comment by mairaw** [comment]
/cc @DuncanmaMSFT @bradygaster 

My previous feature request was marked as completed but did not implement the removal of the syntax blocks from namespace pages, so I just opened a new one.

**Comment by mairaw** [comment]
And we can now choose which attributes we want to display:
![image](https://cloud.githubusercontent.com/assets/12971179/19176692/70710396-8bf7-11e6-9042-48b2931d3e29.png)

Thanks @svick! Keep your feedback coming.
