### ISSUE TITLE
Use Title Case for Headings

### ISSUE THREAD

**Issue by richlander** [dotnet/core-docs#827]
The headings in the .NET Core Tools are all ALL-CAPS case. We don't do that anywhere else.

Our initial plan was to make these docs available as "man pages". If and when we do that, we can have a tool that converts the titles back to ALL-CAPS. For readability on the web, Title Case is better.

Example: https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test

Counter Example: https://git-scm.com/docs/git-bisect

The Git docs use ALL-CAPS case and it mostly works, but there font (and color) lends itself to that. Those docs are also "man page" first, which the .NET Core docs are not.

/cc @BillWagner, @blackdwarf

**Comment by blackdwarf** [comment]
@richlander true, these were MD files from the manpages (and they are still like that :)) We can change easily.

**Comment by mairaw** [comment]
Microsoft guidelines is to use sentence case, not title case, so I've added that as our guidance and opened issue #808 to address that, so I'd close this one.
