### ISSUE TITLE
RID catalog is out of date

### ISSUE THREAD

**Issue by svick** [dotnet/core-docs#829]
It seems [the RID catalog](https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog#using-rids) is not up to date with 1.0 RTM. But I'm not sure which RIDs should be listed here, so I'm creating this issue to discuss that.

[Here is a list of all the RIDs](https://gist.github.com/svick/eb084a68e50547f36b1022a50f3f2982), based on [Microsoft.NETCore.Platforms/runtime.json](https://github.com/dotnet/corefx/blob/release/1.0.0/pkg/Microsoft.NETCore.Platforms/runtime.json). 

Ignoring RIDs that can't actually be installed on a machine (e.g. `any`, `win` or `win7`), RIDs that are not listed fall within several categories. For each category, it should be decided whether to list it in the catalog or not.

* Windows 8+ ARM: I think those should be included, assuming they are supported.
* Windows 8.1: Windows 7, 8 and 10 are currently listed, 8.1 isn't. It should probably be included, since someone asked about it in a comment.
* Windows AOT: No idea.
* Oracle Linux (`ol`): Should be included.
* CentOS: `centos.7.1-x64` is included in the catalog, but does not seem to actually be a valid RID, it should be removed.
* Debian: `debian.8.2-x64` is in the same situation as CentOS, should be removed.
* Ubuntu: 15.10 and 16.04 should be added.
* Fedora: Should be added.
* OpenSUSE: Should be added.

**Comment by mairaw** [comment]
@blackdwarf can you take a look at this issue?
