### ISSUE TITLE
`Microservices hosted in Docker` steps seem out of date

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/core-docs#830]
The [Load into Docker](https://github.com/dotnet/core-docs/blob/master/docs/csharp/tutorials/microservices.md#load-into-docker) of the [Microservices hosted in Docker](https://github.com/dotnet/core-docs/blob/master/docs/csharp/tutorials/microservices.md) seem out of date and a little heavy handed.

1. The section starts by going over the contents of the Dockerfile created by the asp.net template.  A lot of this content appears to have changed.  The current Dockerfile is not based on microsoft/dotnet:onbuild.  It doesn't load SQLite.

 Here is what the Dockerfile looks like that yo generated for me.
 '''
 FROM microsoft/dotnet:latest

 COPY . /app

 WORKDIR /app

 RUN ["dotnet", "restore"]
 
 RUN ["dotnet", "build"]
 
 EXPOSE 5000/tcp

 ENTRYPOINT ["dotnet", "run", "--server.urls", "http://0.0.0.0:5000"]
 '''

2. I don't see the reason to create a new docker machine called 'weather-service'.  This seems heavy handed and isn't necessary.

Aside from that it may be useful to include a step to attach to the running container so that the user can inspect the log output.  This can be useful when diagnosing problems on why the site is not responding.

**Comment by MichaelSimons** [comment]
@BillWagner, @dleeapho

**Comment by BillWagner** [comment]
See also #462
