### ISSUE TITLE
C# Productivity Features in Visual Studio

### ISSUE THREAD

**Issue by kuhlenh** [dotnet/core-docs#872]
A large number of customers have no idea what our productivity features are inside Visual Studio. This will be referenced from VS.com.

Below is my rough outline, with some parts filled.

---
# required metadata

title: C# Productivity Features  | .NET & Visual Studio
description: Visual Studio offers many features that will help you be more productive as you build and innovate in C# and Visual Basic. 
keywords:
author: kuhlenh
manager: wpickett
ms.date: [CREATION/UPDATE DATE]
ms.topic: article
ms.prod: .net-core
ms.technology: .net-core-technologies
ms.assetid: [GET ONE FROM guidgenerator.com]

---

# C# Productivity Features

## Code navigation
Navigate your code to quickly find types, open files, and identify everywhere a type is referenced in your codebase. 
### Go To Definition (GTD)
Takes you to the source of a type/member/local/etc. It uses Roslyn’s internal understanding of the code to make sure it takes you to the right member—even when there are many overloads or if you code is using a lot of type inference. **Go To Definition** causes your context (the active file, current line, and cursor position) to switch to the definition location (often opening a file in a new tab).
#### Metadata As Source
If you are trying to get the source for a type defined in a reference assembly, we will display "**Metadata As Source**"—a header file view of the corresponding type and its members. This will keep you inside the editor and you can continue to navigate other members/types directly from the **Metadata As Source** view using **Go To Definition**.
#### Backwards and forwards navigation
If you use **Go To Definition** a lot, you’ll probably find yourself wanting to go “back” to where you invoked **Go To Definition** from.  There is a keybinding for this:
* `Ctrl + -` : Takes you back in the GTD stack, to the last place you invoked GTD
* `Ctrl + Shift + -` :  Takes you forward in the GTD stack, to the last place you invoked back

| C# 2005 Profile  | Default Profile  |
|:----------------:|:----------------:|
| `F12`            |                  |

#### Overview
What are the components of code analysis?
* Context Action (aka “Quick Action”) 
* Refactoring 
* Code Diagnostic
* Code Style

What are the severity levels of analyzers?
* Error
* Warning 
* Info/Suggestion
* Hidden

### Context Actions
* Generate [Type, Method, Properties, Constructor, Overrides, Local variables, Implement Abstract Class/Interface]
* Add missing case
* Add braces
* Add Using for types in reference assemblies
* Add Using for types in NuGet.org
* Fuzzy matching
* Lambda simplifier (delgate simplifier)
* Encapsulate field
* Convert property to method
* Convert method to property
* Remove redundant qualifier
* Remove redundant cast
* Remove unnecessary usings
* Use string interpolation

### Refactoring 
* Rename
* Extract [method/interface]
* Move type to matching file
* Sync file name and type
* Inline temporary variable
* Change method signature

### Code Diagnostics
* FX Cop Analyzers

### Code Style
* Prefer var/explicit type
* Prefer this. and Me
* Prefer predefined/framework type
* Naming Conventions
* Format selection
* Format document

## Code assistance
* Code snippets
* Move selection up/down
* Extend/shrink selection

### Scripting dialect
* "# directives*
    - #help
    - #clear or #cls
    - #load
    - #r
    - #reset
* top-level "script" variables
* asynchronous execution

### Interactive Features
* Evaluate code snippets
* Navigate command history
* Navigate command history by prefix
* Navigate the editor
* Copy/paste
* Multi-line support
* Command selection
* Clear submission

### Working with a projects
* Send snippet from editor to Interactive
* Initialize Interactive with a project's context

### Write your own code analyzer/fixer
link to page on how to get started with roslyn analyzers

#### Fonts & colors
* Color of identifiers, types, keywords

#### Reset windows to default

**Comment by kuhlenh** [comment]
would love your thoughts on whether I should combine C# and VB in this documentation (not all features are for both languages, but there is a huge overlap).

**Comment by stevehoag** [comment]
We’ve just gone through an exercise of separating the combined VB/C# docs. The separated topics are getting higher satisfaction ratings, so I think we should go forward with creating separate topics for each language even when there is substantial duplication.

**Comment by kuhlenh** [comment]
Closing and moving to a different repro.
