### ISSUE TITLE
docs/core/tools/project-json.md - unclear what is the default for System.GC.RetainVM

### ISSUE THREAD

**Issue by idofl** [dotnet/core-docs#878]
In the configProperties section, there is an explanation on the various GC knobs. For **System.GC.Server** is says that the default is false, but for **System.GC.RetainVM** it only says the options, and doesn't specify the default.

**Comment by mairaw** [comment]
@livarcocc can you confirm what's the default value for System.GC.RetainVM in the project.json file?

**Comment by livarcocc** [comment]
@gkhanna79 Is this something determined by the host?

**Comment by gkhanna79** [comment]
The host does not set anything here. If any of these values are present in the config file, the host simply passes them to the runtime who makes the determination of the next steps.

@Maoni0 can comment on the defaults for RetainVM.

**Comment by Maoni0** [comment]
The default is false, meaning if this does not appear in any sort of config or passed in any startup flags, this is off. 

As far as the default *config* value, I would think that's just in the config generated by whatever tool you are using to create your project. And I dunno what the current generated config looks like. I have not used the current dotnet tool to create a project myself.

**Comment by mairaw** [comment]
Thanks @Maoni0. You answered what I needed. I'll add that the default is false.
