### ISSUE TITLE
Add samples structure

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#91]
We need to add the structure for the sample code so that people can start adding compilable sample code.

**Comment by cartermp** [comment]
@richlander @BethMassi @blackdwarf because there is a requirement that samples be compilable projects, this leaves us a decision -- do we accept Visual Studio projects, non-VS projects, or both?

I'm leaning towards accepting both, but preferring purely folder-based, CLI projects.

**Comment by cartermp** [comment]
Talked with @BethMassi and we decided to require these samples to be cross-platform, which means no Windows or Visual Studio dependencies.

**Comment by matthewreily** [comment]
So are we talking about a .cs file with a project.json that could be ran using dnx? Or just the .cs file?

**Comment by BethMassi** [comment]
project.json and the cs file. @cartermp is working on the first sample so we have an example.

**Comment by matthewreily** [comment]
Great, I like that better than having solution files and adding to the complexity.

**Comment by cartermp** [comment]
I added a stub that should give you an idea of what it would look like (pending merge, but should give an idea).

**Comment by matthewreily** [comment]
Great! Thank you.

**Comment by cartermp** [comment]
@matthewreily the structure is in place!  You should be able to write some awesome samples now.

**Comment by matthewreily** [comment]
Thank you sir and also thanks to @BethMassi!  I'm attending a conference
today but will start at it tomorrow.
