### ISSUE TITLE
Include MSTest or swap XUnit with MSTest on tutorial "using-on-windows"

### ISSUE THREAD

**Issue by ncarandini** [dotnet/core-docs#915]
Hi,
I successfully tried to use MSTest on the TestLibrary project, and I think it would be useful to modify the tutorial to include the MSTest instructions or to swap XUnit in favor of MSTest.
If you think is a good idea I can do it by myself and create a PR.

@cartermp

[Link to tutorial](https://docs.microsoft.com/en-us/dotnet/articles/core/tutorials/using-on-windows
)
[Link to GitHub page](https://github.com/dotnet/core-docs/blob/master/docs/core/tutorials/using-on-windows.md)

**Comment by BillWagner** [comment]
@ncarandini Thank you for raising this issue.

I agree that we should cover MSTest.  I believe it would be better for consumers if it were a different topic, parallel to the current topic. The flow would be better to have a cohesive tutorial for xUnit, and a second for MSTest than for one topic that switches back and forth between those two tools. 

Would you agree?

**Comment by ncarandini** [comment]
Yes, interleaving xUnit and MSTest will be confusing, at best.
When you say two topic, do you mean a subsequent topic in the same document, maybe with a common prehamble like "[...] You can use either xUnit or MSTest[...]" followed by two distinct topic:
- Writing the test project with xUnit
- Writing the test project with MSTest
or another document?

**Comment by BillWagner** [comment]
I think it's a separate document, in the same directory. We make sure to cross-link the topics, and add the new one in the TOC.md so readers can easily find both.

**Comment by ncarandini** [comment]
Ok, perfect. I can write a draft, if you like.

**Comment by BillWagner** [comment]
That would be wonderful. If you want any of us to review outlines or early drafts, just make a PR and add the "WIP" label.

**Comment by ncarandini** [comment]
Thanks, is my first contrib and I love to try this.

**Comment by ncarandini** [comment]
Done, but I've no rights to add the "WIP" label.

**Comment by mairaw** [comment]
I've added the label. We'll review it soon.

**Comment by ncarandini** [comment]
Hi Maira,
Doing some testing I've just discovered that the latest preview version of MSTest packages (the ones I've written on the proposed article) we can skip step 9 because the solution builds with "imports": "dnxcore50".
Can this change be made directly by the reviewer?

**Comment by mairaw** [comment]
Hi @ncarandini. You can change the article. Use the same branch you used for submitting your PR and the PR will be automatically updated when you push the changes. Thanks for your contribution!

**Comment by ncarandini** [comment]
Thanks, didn't know that, I'm still a rookie on PRs :-)
