### ISSUE TITLE
Add RIDs for the windows servers

### ISSUE THREAD

**Issue by zhengchun** [dotnet/core-docs#923]
Hello,recently i'm want to publish my .net core app to windows 2008 r2,but im not found that list in the [offcial document](https://docs.microsoft.com/en-us/dotnet/articles/core/rid-catalog).

googling and have solved my problem by this : [Which Versions of Windows Server Match the .NET Core Runtime RID's](http://stackoverflow.com/questions/37838394/which-versions-of-windows-server-match-the-net-core-runtime-rids),can you list RIDs for the windows server? i hope this can help.

**Comment by mairaw** [comment]
We're in the process of updating that article. I'll make sure this is covered too.

**Comment by mairaw** [comment]
Thanks for your feedback. The article was updated and now included the Windows Server RIDs.
