### ISSUE TITLE
The EXPRESSION - TRANSLATION table is messed up on the MSDN page for the Computation Expressions

### ISSUE THREAD

**Issue by mrakgr** [dotnet/core-docs#926]
The .md file shows it fine on Chrome, but [this page does not display it properly](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/computation-expressions).

**Comment by mairaw** [comment]
It's probably the pipes inside the inline code that is messing with that. @dend you had another topic where you had to HTML literals to workaround this issue no? It's interesting that GitHub knows how to handle that. I'll open a bug to the site and see if they can mimic the GitHub behavior.

**Comment by cartermp** [comment]
Yep, looks like we missed some `<code>` blocks.  I'll get a PR out.

**Comment by cartermp** [comment]
Fixed!  This should go live in a day or two.
